

--region [dbo].[pa_DeletegesZonasByCodLocal]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesZonasByCodLocal]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesZonasByCodLocal]
	@CodLocal int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesZonas]
WHERE
	[CodLocal] = @CodLocal


