

--region [dbo].[pa_DeletegesZonasByCodDispositivo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesZonasByCodDispositivo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesZonasByCodDispositivo]
	@CodDispositivo int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesZonas]
WHERE
	[CodDispositivo] = @CodDispositivo


