

--region [dbo].[pa_DeletegesHistoricoFactura2011]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesHistoricoFactura2011]
-- Date Generated: miércoles, 29 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesHistoricoFactura2011]
	@CodFactura uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesHistoricoFactura2011]
WHERE
	[CodFactura] = @CodFactura

--endregion


