

--region [dbo].[pa_DeleteGesArticuloClaseConEscandallosByCodClasePadre]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeleteGesArticuloClaseConEscandallosByCodClasePadre]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeleteGesArticuloClaseConEscandallosByCodClasePadre]
	@CodClasePadre int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[GesArticuloClaseConEscandallo]
WHERE
	[CodClasePadre] = @CodClasePadre


