

--region [dbo].[pa_Deletegeshistoricofactique2011]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_Deletegeshistoricofactique2011]
-- Date Generated: miércoles, 29 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_Deletegeshistoricofactique2011]
	@CodDetalle uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[geshistoricofactique2011]
WHERE
	[CodDetalle] = @CodDetalle

--endregion


