

--region [dbo].[pa_DeletegesEstatu]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesEstatu]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesEstatu]
	@CodEstatus int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesEstatus]
WHERE
	[CodEstatus] = @CodEstatus

--endregion


