

--region [dbo].[pa_DeletegesPoblacion]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPoblacion]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPoblacion]
	@CodPoblacion int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPoblacion]
WHERE
	[CodPoblacion] = @CodPoblacion

--endregion


