

--region [dbo].[pa_DeletegesPagoForma]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPagoForma]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPagoForma]
	@CodPago int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPagoForma]
WHERE
	[CodPago] = @CodPago

--endregion


