

--region [dbo].[pa_DeletegesClaseCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesClaseCliente]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesClaseCliente]
	@CodClase int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesClaseCliente]
WHERE
	[CodClase] = @CodClase

--endregion


