

--region [dbo].[pa_DeletegesMesa]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesMesa]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesMesa]
	@CodMesa int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesMesa]
WHERE
	[CodMesa] = @CodMesa

--endregion


