

--region [dbo].[pa_DeletegesClientesByCodClase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesClientesByCodClase]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesClientesByCodClase]
	@CodClase int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesCliente]
WHERE
	[CodClase] = @CodClase


