

--region [dbo].[pa_DeleteTotalArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeleteTotalArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeleteTotalArqueo]
	@Codigo bigint
AS

SET NOCOUNT ON

DELETE FROM [dbo].[TotalArqueo]
WHERE
	[Codigo] = @Codigo

--endregion


