
--region [dbo].[pa_DeletegesPedidosByCodTrabajador]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedidosByCodTrabajador]
-- Date Generated: miércoles, 19 de octubre de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedidosByCodTrabajador]
	@CodTrabajador int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedido]
WHERE
	[CodTrabajador] = @CodTrabajador

