

--region [dbo].[pa_DeletegesArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesArqueo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesArqueo]
	@CodArqueo uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesArqueo]
WHERE
	[CodArqueo] = @CodArqueo

--endregion


