

--region [dbo].[pa_DeletegesZona]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesZona]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesZona]
	@CodZona int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesZonas]
WHERE
	[CodZona] = @CodZona

--endregion


