

--region [dbo].[pa_DeletegesTrabajadorsByClave]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesTrabajadorsByClave]
-- Date Generated: lunes, 04 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesTrabajadorsByClave]
	@Clave char(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesTrabajador]
WHERE
	[Clave] = @Clave

--endregion


