
--region [dbo].[pa_DeletegesPedido]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedido]
-- Date Generated: miércoles, 19 de octubre de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedido]
	@CodPedido uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedido]
WHERE
	[CodPedido] = @CodPedido

--endregion

