

--region [dbo].[pa_DeletegesEscandallosByCodProducto]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesEscandallosByCodProducto]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesEscandallosByCodProducto]
	@CodProducto uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesEscandallo]
WHERE
	[CodProducto] = @CodProducto


