

--region [dbo].[pa_DeletegesAnulacionTipo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesAnulacionTipo]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesAnulacionTipo]
	@CodTipo int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesAnulacionTipo]
WHERE
	[CodTipo] = @CodTipo

--endregion


