

--region [dbo].[pa_DeletegesCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesCliente]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesCliente]
	@CodCliente int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesCliente]
WHERE
	[CodCliente] = @CodCliente

--endregion


