

--region [dbo].[pa_DeletegesPeriodo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPeriodo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPeriodo]
	@CodPeriodo int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPeriodos]
WHERE
	[CodPeriodo] = @CodPeriodo

--endregion


