

--region [dbo].[pa_DeletegesCatalogo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesCatalogo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesCatalogo]
	@CodCatalogo int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesCatalogo]
WHERE
	[CodCatalogo] = @CodCatalogo

--endregion


