

--region [dbo].[pa_DeletegesFacturasByMesaAndClienteAndEstado]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesFacturasByMesaAndClienteAndEstado]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesFacturasByMesaAndClienteAndEstado]
	@Mesa char(50),
	@Cliente varchar(100),
	@Estado varchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesFactura]
WHERE
	[Mesa] = @Mesa
	AND [Cliente] = @Cliente
	AND [Estado] = @Estado

--endregion


