

--region [dbo].[pa_DeletegesCola]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesCola]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesCola]
	@CodCola int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesCola]
WHERE
	[CodCola] = @CodCola

--endregion


