

--region [dbo].[pa_DeleteGesArticuloClaseConEscandallo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeleteGesArticuloClaseConEscandallo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeleteGesArticuloClaseConEscandallo]
	@Codigo int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[GesArticuloClaseConEscandallo]
WHERE
	[Codigo] = @Codigo

--endregion


