

--region [dbo].[pa_DeletegesArticulosByCodGrupoCompra]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesArticulosByCodGrupoCompra]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesArticulosByCodGrupoCompra]
	@CodGrupoCompra int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesArticulo]
WHERE
	[CodGrupoCompra] = @CodGrupoCompra


