

--region [dbo].[pa_DeletegesArticulosByCodEnvase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesArticulosByCodEnvase]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesArticulosByCodEnvase]
	@CodEnvase int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesArticulo]
WHERE
	[CodEnvase] = @CodEnvase


