

--region [dbo].[pa_DeleteTotalArqueosByFecha]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeleteTotalArqueosByFecha]
-- Date Generated: viernes, 19 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeleteTotalArqueosByFecha]
	@Fecha datetime
AS

SET NOCOUNT ON

DELETE FROM [dbo].[TotalArqueo]
WHERE
	[Fecha] = @Fecha

--endregion


