

--region [dbo].[pa_DeletegesPedidoDetallesByCodArticulo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedidoDetallesByCodArticulo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedidoDetallesByCodArticulo]
	@CodArticulo int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedidoDetalle]
WHERE
	[CodArticulo] = @CodArticulo


