

--region [dbo].[pa_DeletegesProveedore]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesProveedore]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesProveedore]
	@CodProveedor int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesProveedores]
WHERE
	[CodProveedor] = @CodProveedor

--endregion


