

--region [dbo].[pa_DeleteTotalDetalleArqueosByCodigo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeleteTotalDetalleArqueosByCodigo]
-- Date Generated: viernes, 19 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeleteTotalDetalleArqueosByCodigo]
	@Codigo bigint
AS

SET NOCOUNT ON

DELETE FROM [dbo].[TotalDetalleArqueo]
WHERE
	[Codigo] = @Codigo


