
--region [dbo].[pa_DeletegesTrabajadorsByAndCodEstatus]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesTrabajadorsByAndCodEstatus]
-- Date Generated: miércoles, 18 de diciembre de 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesTrabajadorsByAndCodEstatus]
	@CodEstatus int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesTrabajador]
WHERE
	[CodEstatus] = @CodEstatus

