

--region [dbo].[pa_DeletegesActividade]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesActividade]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesActividade]
	@CodActividad int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesActividades]
WHERE
	[CodActividad] = @CodActividad

--endregion


