

--region [dbo].[pa_DeletegesCatalogosByCodFormatoPedido]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesCatalogosByCodFormatoPedido]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesCatalogosByCodFormatoPedido]
	@CodFormatoPedido int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesCatalogo]
WHERE
	[CodFormatoPedido] = @CodFormatoPedido


