
--region [dbo].[pa_DeletegesPedidosByCodProveedor]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedidosByCodProveedor]
-- Date Generated: miércoles, 19 de octubre de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedidosByCodProveedor]
	@CodProveedor int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedido]
WHERE
	[CodProveedor] = @CodProveedor

