
--region [dbo].[pa_DeletegesTrabajadorsByAndCodSeguridad]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesTrabajadorsByAndCodSeguridad]
-- Date Generated: miércoles, 18 de diciembre de 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesTrabajadorsByAndCodSeguridad]
	@CodSeguridad int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesTrabajador]
WHERE
	[CodSeguridad] = @CodSeguridad

