

--region [dbo].[pa_DeletegesFichaje]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesFichaje]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesFichaje]
	@CodFichaje uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesFichaje]
WHERE
	[CodFichaje] = @CodFichaje

--endregion


