

--region [dbo].[pa_DeletegesPedidosByAlbaran]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedidosByAlbaran]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedidosByAlbaran]
	@Albaran nvarchar(150)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedido]
WHERE
	[Albaran] = @Albaran

--endregion


