

--region [dbo].[pa_DeletegesCatalogosByCodProveedor]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesCatalogosByCodProveedor]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesCatalogosByCodProveedor]
	@CodProveedor int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesCatalogo]
WHERE
	[CodProveedor] = @CodProveedor


