

--region [dbo].[pa_DeletegesEscandallo_NumsByCodClase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesEscandallo_NumsByCodClase]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesEscandallo_NumsByCodClase]
	@CodClase int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesEscandallo_Num]
WHERE
	[CodClase] = @CodClase


