

--region [dbo].[pa_DeletegesFacTique]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesFacTique]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesFacTique]
	@CodDetalle uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesFacTique]
WHERE
	[CodDetalle] = @CodDetalle

--endregion


