

--region [dbo].[pa_DeletegesFamiliasByCodZona]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesFamiliasByCodZona]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesFamiliasByCodZona]
	@CodZona int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesFamilia]
WHERE
	[CodZona] = @CodZona


