
--region [dbo].[pa_DeletegesFacturasByAndCodTrabajador]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesFacturasByAndCodTrabajador]
-- Date Generated: miércoles, 18 de diciembre de 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesFacturasByAndCodTrabajador]
	@CodTrabajador uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesFactura]
WHERE
	[CodTrabajador] = @CodTrabajador

