

--region [dbo].[pa_DeletegesPedidoDetalle]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedidoDetalle]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedidoDetalle]
	@CodDetalle uniqueidentifier
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedidoDetalle]
WHERE
	[CodDetalle] = @CodDetalle

--endregion


