

--region [dbo].[pa_DeletegesSeguridad]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesSeguridad]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesSeguridad]
	@CodSeguridad int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesSeguridad]
WHERE
	[CodSeguridad] = @CodSeguridad

--endregion


