

--region [dbo].[pa_DeletegesPedidoDetallesByPedido]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_DeletegesPedidoDetallesByPedido]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_DeletegesPedidoDetallesByPedido]
	@Pedido datetime
AS

SET NOCOUNT ON

DELETE FROM [dbo].[gesPedidoDetalle]
WHERE
	[Pedido] = @Pedido

--endregion


