

--region [dbo].[pa_InsertUpdategesEscandallo_Num]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesEscandallo_Num]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesEscandallo_Num]
	@CodEscandallo uniqueidentifier,
	@CodProducto uniqueidentifier,
	@CodClase int,
	@Cantidad decimal(18, 4),
	@CodMagnitud int,
	@CodProducto_Num int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodEscandallo] FROM [dbo].[gesEscandallo_Num] WHERE [CodEscandallo] = @CodEscandallo)
BEGIN
	UPDATE [dbo].[gesEscandallo_Num] SET
		[CodProducto] = @CodProducto,
		[CodClase] = @CodClase,
		[Cantidad] = @Cantidad,
		[CodMagnitud] = @CodMagnitud,
		[CodProducto_Num] = @CodProducto_Num
	WHERE
		[CodEscandallo] = @CodEscandallo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesEscandallo_Num] (
		[CodEscandallo],
		[CodProducto],
		[CodClase],
		[Cantidad],
		[CodMagnitud],
		[CodProducto_Num]
	) VALUES (
		@CodEscandallo,
		@CodProducto,
		@CodClase,
		@Cantidad,
		@CodMagnitud,
		@CodProducto_Num
	)
END

--endregion


