

--region [dbo].[pa_InsertUpdategesPoblacion]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesPoblacion]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesPoblacion]
	@CodPoblacion int,
	@Descripcion char(20)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodPoblacion] FROM [dbo].[gesPoblacion] WHERE [CodPoblacion] = @CodPoblacion)
BEGIN
	UPDATE [dbo].[gesPoblacion] SET
		[Descripcion] = @Descripcion
	WHERE
		[CodPoblacion] = @CodPoblacion
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesPoblacion] (
		[CodPoblacion],
		[Descripcion]
	) VALUES (
		@CodPoblacion,
		@Descripcion
	)
END

--endregion


