

--region [dbo].[pa_InsertgesActividade]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesActividade]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesActividade]
	@CodActividad int,
	@Descripcion varchar(100),
	@Activa bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesActividades] (
	[CodActividad],
	[Descripcion],
	[Activa]
) VALUES (
	@CodActividad,
	@Descripcion,
	@Activa
)

--endregion


