

--region [dbo].[pa_InsertgesClaseCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesClaseCliente]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesClaseCliente]
	@CodClase int,
	@Descripcion varchar(100)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesClaseCliente] (
	[CodClase],
	[Descripcion]
) VALUES (
	@CodClase,
	@Descripcion
)

--endregion


