

--region [dbo].[pa_InsertUpdategesPagoForma]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesPagoForma]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesPagoForma]
	@CodPago int,
	@Descripcion char(100),
	@Activo bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodPago] FROM [dbo].[gesPagoForma] WHERE [CodPago] = @CodPago)
BEGIN
	UPDATE [dbo].[gesPagoForma] SET
		[Descripcion] = @Descripcion,
		[Activo] = @Activo
	WHERE
		[CodPago] = @CodPago
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesPagoForma] (
		[CodPago],
		[Descripcion],
		[Activo]
	) VALUES (
		@CodPago,
		@Descripcion,
		@Activo
	)
END

--endregion


