

--region [dbo].[pa_InsertgesProducto_Num]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesProducto_Num]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesProducto_Num]
	@CodProducto uniqueidentifier,
	@CodGrupo int,
	@CodFamilia int,
	@CodZona int,
	@Descripcion varchar(100),
	@Activo bit,
	@Precio decimal(18, 2),
	@ConEscandallo bit,
	@CodProducto_Num int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesProducto_Num] (
	[CodProducto],
	[CodGrupo],
	[CodFamilia],
	[CodZona],
	[Descripcion],
	[Activo],
	[Precio],
	[ConEscandallo]
) VALUES (
	@CodProducto,
	@CodGrupo,
	@CodFamilia,
	@CodZona,
	@Descripcion,
	@Activo,
	@Precio,
	@ConEscandallo
)

SET @CodProducto_Num = SCOPE_IDENTITY()

--endregion


