
--region [dbo].[pa_InsertgesFacTique_Num]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 5.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesFacTique_Num]
-- Date Generated: miércoles, 18 de diciembre de 2013
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesFacTique_Num]
	@CodFactura uniqueidentifier,
	@CodProducto uniqueidentifier,
	@Detalle varchar(150),
	@Unidad int,
	@Importe decimal(18, 2),
	@SubTotal decimal(18, 2),
	@CodTrabajador uniqueidentifier,
	@Suceso char(50),
	@Operacion char(50),
	@Fecha datetime,
	@Orden int,
	@CodDispositivo int,
	@CodActividad int,
	@Relacion uniqueidentifier,
	@Estadio char(50),
	@CodCola int,
	@CodProducto_Num int,
	@FechaNegocio datetime,
	@CodDetalle uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodDetalle = NEWID()

INSERT INTO [dbo].[gesFacTique_Num] (
	[CodDetalle],
	[CodFactura],
	[CodProducto],
	[Detalle],
	[Unidad],
	[Importe],
	[SubTotal],
	[CodTrabajador],
	[Suceso],
	[Operacion],
	[Fecha],
	[Orden],
	[CodDispositivo],
	[CodActividad],
	[Relacion],
	[Estadio],
	[CodCola],
	[CodProducto_Num],
	[FechaNegocio]
) VALUES (
	@CodDetalle,
	@CodFactura,
	@CodProducto,
	@Detalle,
	@Unidad,
	@Importe,
	@SubTotal,
	@CodTrabajador,
	@Suceso,
	@Operacion,
	@Fecha,
	@Orden,
	@CodDispositivo,
	@CodActividad,
	@Relacion,
	@Estadio,
	@CodCola,
	@CodProducto_Num,
	@FechaNegocio
)

--endregion

