

--region [dbo].[pa_InsertgesCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesCliente]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesCliente]
	@CodCliente int,
	@Nombre varchar(50),
	@Apellidos varchar(100),
	@Empresa varchar(100),
	@Activo bit,
	@CIF char(50),
	@Direccion varchar(100),
	@Localidad varchar(50),
	@Provincia varchar(50),
	@CP char(10),
	@CodClase int,
	@Telefono1 char(10)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesCliente] (
	[CodCliente],
	[Nombre],
	[Apellidos],
	[Empresa],
	[Activo],
	[CIF],
	[Direccion],
	[Localidad],
	[Provincia],
	[CP],
	[CodClase],
	[Telefono1]
) VALUES (
	@CodCliente,
	@Nombre,
	@Apellidos,
	@Empresa,
	@Activo,
	@CIF,
	@Direccion,
	@Localidad,
	@Provincia,
	@CP,
	@CodClase,
	@Telefono1
)

--endregion


