

--region [dbo].[pa_InsertgesProducto]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesProducto]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesProducto]
	@CodGrupo int,
	@CodFamilia int,
	@CodZona int,
	@Descripcion varchar(100),
	@Activo bit,
	@Precio decimal(18, 2),
	@CodProducto uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodProducto = NEWID()

INSERT INTO [dbo].[gesProducto] (
	[CodProducto],
	[CodGrupo],
	[CodFamilia],
	[CodZona],
	[Descripcion],
	[Activo],
	[Precio]
) VALUES (
	@CodProducto,
	@CodGrupo,
	@CodFamilia,
	@CodZona,
	@Descripcion,
	@Activo,
	@Precio
)

--endregion


