

--region [dbo].[pa_InsertUpdategesSeguridad]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesSeguridad]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesSeguridad]
	@CodSeguridad int,
	@Descripcion varchar(50),
	@Activa bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodSeguridad] FROM [dbo].[gesSeguridad] WHERE [CodSeguridad] = @CodSeguridad)
BEGIN
	UPDATE [dbo].[gesSeguridad] SET
		[Descripcion] = @Descripcion,
		[Activa] = @Activa
	WHERE
		[CodSeguridad] = @CodSeguridad
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesSeguridad] (
		[CodSeguridad],
		[Descripcion],
		[Activa]
	) VALUES (
		@CodSeguridad,
		@Descripcion,
		@Activa
	)
END

--endregion


