

--region [dbo].[pa_InsertUpdategesAnulacione]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesAnulacione]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesAnulacione]
	@CodAnulacion int,
	@CodTrabajador int,
	@Fecha datetime,
	@CodProducto int,
	@CodTipo int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodAnulacion] FROM [dbo].[gesAnulaciones] WHERE [CodAnulacion] = @CodAnulacion)
BEGIN
	UPDATE [dbo].[gesAnulaciones] SET
		[CodTrabajador] = @CodTrabajador,
		[Fecha] = @Fecha,
		[CodProducto] = @CodProducto,
		[CodTipo] = @CodTipo
	WHERE
		[CodAnulacion] = @CodAnulacion
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesAnulaciones] (
		[CodAnulacion],
		[CodTrabajador],
		[Fecha],
		[CodProducto],
		[CodTipo]
	) VALUES (
		@CodAnulacion,
		@CodTrabajador,
		@Fecha,
		@CodProducto,
		@CodTipo
	)
END

--endregion


