

--region [dbo].[pa_InsertUpdategesCatalogo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesCatalogo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesCatalogo]
	@CodCatalogo int,
	@CodProveedor int,
	@CodArticulo int,
	@CodFormatoPedido int,
	@CodEmpaquetado int,
	@Precio decimal(18, 4),
	@Pedir bit,
	@IVA decimal(18, 2),
	@Debe_haber decimal(18, 2),
	@Importe decimal(18, 4),
	@Contenido_unidad decimal(18, 2),
	@Contenido_caja decimal(18, 2),
	@PedirCajas bit,
	@Preferente bit,
	@PrecioUltimoCompra decimal(18, 2),
	@PrecioMedioCompra decimal(18, 2)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodCatalogo] FROM [dbo].[gesCatalogo] WHERE [CodCatalogo] = @CodCatalogo)
BEGIN
	UPDATE [dbo].[gesCatalogo] SET
		[CodProveedor] = @CodProveedor,
		[CodArticulo] = @CodArticulo,
		[CodFormatoPedido] = @CodFormatoPedido,
		[CodEmpaquetado] = @CodEmpaquetado,
		[Precio] = @Precio,
		[Pedir] = @Pedir,
		[IVA] = @IVA,
		[Debe_haber] = @Debe_haber,
		[Importe] = @Importe,
		[Contenido_unidad] = @Contenido_unidad,
		[Contenido_caja] = @Contenido_caja,
		[PedirCajas] = @PedirCajas,
		[Preferente] = @Preferente,
		[PrecioUltimoCompra] = @PrecioUltimoCompra,
		[PrecioMedioCompra] = @PrecioMedioCompra
	WHERE
		[CodCatalogo] = @CodCatalogo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesCatalogo] (
		[CodCatalogo],
		[CodProveedor],
		[CodArticulo],
		[CodFormatoPedido],
		[CodEmpaquetado],
		[Precio],
		[Pedir],
		[IVA],
		[Debe_haber],
		[Importe],
		[Contenido_unidad],
		[Contenido_caja],
		[PedirCajas],
		[Preferente],
		[PrecioUltimoCompra],
		[PrecioMedioCompra]
	) VALUES (
		@CodCatalogo,
		@CodProveedor,
		@CodArticulo,
		@CodFormatoPedido,
		@CodEmpaquetado,
		@Precio,
		@Pedir,
		@IVA,
		@Debe_haber,
		@Importe,
		@Contenido_unidad,
		@Contenido_caja,
		@PedirCajas,
		@Preferente,
		@PrecioUltimoCompra,
		@PrecioMedioCompra
	)
END

--endregion


