

--region [dbo].[pa_InsertgesFichaje]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesFichaje]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesFichaje]
	@CodTrabajador int,
	@Nombre varchar(100),
	@Apellidos varchar(100),
	@Entrada datetime,
	@Salida datetime,
	@CodPeriodo int,
	@Periodo char(50),
	@CodLocal int,
	@Centro varchar(100),
	@CodZona int,
	@Zona varchar(100),
	@CodDispositivo int,
	@Estado char(50),
	@CodFichaje uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodFichaje = NEWID()

INSERT INTO [dbo].[gesFichaje] (
	[CodFichaje],
	[CodTrabajador],
	[Nombre],
	[Apellidos],
	[Entrada],
	[Salida],
	[CodPeriodo],
	[Periodo],
	[CodLocal],
	[Centro],
	[CodZona],
	[Zona],
	[CodDispositivo],
	[Estado]
) VALUES (
	@CodFichaje,
	@CodTrabajador,
	@Nombre,
	@Apellidos,
	@Entrada,
	@Salida,
	@CodPeriodo,
	@Periodo,
	@CodLocal,
	@Centro,
	@CodZona,
	@Zona,
	@CodDispositivo,
	@Estado
)

--endregion


