

--region [dbo].[pa_InsertgesZona]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesZona]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesZona]
	@CodLocal int,
	@CodDispositivo int,
	@CodActividad int,
	@Nombre varchar(100),
	@Activa bit,
	@Tipo char(50),
	@CodZona int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesZonas] (
	[CodLocal],
	[CodDispositivo],
	[CodActividad],
	[Nombre],
	[Activa],
	[Tipo]
) VALUES (
	@CodLocal,
	@CodDispositivo,
	@CodActividad,
	@Nombre,
	@Activa,
	@Tipo
)

SET @CodZona = SCOPE_IDENTITY()

--endregion


