

--region [dbo].[pa_InsertUpdategesEnvase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesEnvase]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesEnvase]
	@CodEnvase int,
	@Descripcion char(50),
	@Activo bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodEnvase] FROM [dbo].[gesEnvase] WHERE [CodEnvase] = @CodEnvase)
BEGIN
	UPDATE [dbo].[gesEnvase] SET
		[Descripcion] = @Descripcion,
		[Activo] = @Activo
	WHERE
		[CodEnvase] = @CodEnvase
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesEnvase] (
		[CodEnvase],
		[Descripcion],
		[Activo]
	) VALUES (
		@CodEnvase,
		@Descripcion,
		@Activo
	)
END

--endregion


