

--region [dbo].[pa_InsertgesArticulo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesArticulo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesArticulo]
	@CodArticulo int,
	@CodGrupo int,
	@CodFamilia int,
	@CodEnvase int,
	@CodMagnitud int,
	@CodGrupoCompra int,
	@CodSectorPedido int,
	@CodClase int,
	@Descripcion varchar(100),
	@Activo bit,
	@Contenido_unidad decimal(18, 2),
	@Contenido_caja decimal(18, 2),
	@Existencias decimal(18, 2),
	@Debe_haber decimal(18, 2),
	@PrecioUltimoCompra decimal(18, 2),
	@PrecioMedioCompra decimal(18, 2)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesArticulo] (
	[CodArticulo],
	[CodGrupo],
	[CodFamilia],
	[CodEnvase],
	[CodMagnitud],
	[CodGrupoCompra],
	[CodSectorPedido],
	[CodClase],
	[Descripcion],
	[Activo],
	[Contenido_unidad],
	[Contenido_caja],
	[Existencias],
	[Debe_haber],
	[PrecioUltimoCompra],
	[PrecioMedioCompra]
) VALUES (
	@CodArticulo,
	@CodGrupo,
	@CodFamilia,
	@CodEnvase,
	@CodMagnitud,
	@CodGrupoCompra,
	@CodSectorPedido,
	@CodClase,
	@Descripcion,
	@Activo,
	@Contenido_unidad,
	@Contenido_caja,
	@Existencias,
	@Debe_haber,
	@PrecioUltimoCompra,
	@PrecioMedioCompra
)

--endregion


