

--region [dbo].[pa_InsertUpdateTotalArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdateTotalArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdateTotalArqueo]
	@Fecha datetime,
	@Total decimal(18, 2),
	@Codigo bigint
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Codigo] FROM [dbo].[TotalArqueo] WHERE [Codigo] = @Codigo)
BEGIN
	UPDATE [dbo].[TotalArqueo] SET
		[Fecha] = @Fecha,
		[Total] = @Total
	WHERE
		[Codigo] = @Codigo
END
ELSE
BEGIN
	INSERT INTO [dbo].[TotalArqueo] (
		[Fecha],
		[Total]
	) VALUES (
		@Fecha,
		@Total
	)
END

--endregion
