

--region [dbo].[pa_InsertUpdategesDispositivo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesDispositivo]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesDispositivo]
	@CodDispositivo int,
	@Nombre varchar(100),
	@Activo bit,
	@Tipo char(20),
	@Imprime_comanda bit,
	@Imprime_tique bit,
	@Imprime_factura bit,
	@Abre_cajon bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodDispositivo] FROM [dbo].[gesDispositivo] WHERE [CodDispositivo] = @CodDispositivo)
BEGIN
	UPDATE [dbo].[gesDispositivo] SET
		[Nombre] = @Nombre,
		[Activo] = @Activo,
		[Tipo] = @Tipo,
		[Imprime_comanda] = @Imprime_comanda,
		[Imprime_tique] = @Imprime_tique,
		[Imprime_factura] = @Imprime_factura,
		[Abre_cajon] = @Abre_cajon
	WHERE
		[CodDispositivo] = @CodDispositivo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesDispositivo] (
		[CodDispositivo],
		[Nombre],
		[Activo],
		[Tipo],
		[Imprime_comanda],
		[Imprime_tique],
		[Imprime_factura],
		[Abre_cajon]
	) VALUES (
		@CodDispositivo,
		@Nombre,
		@Activo,
		@Tipo,
		@Imprime_comanda,
		@Imprime_tique,
		@Imprime_factura,
		@Abre_cajon
	)
END

--endregion


