

--region [dbo].[pa_InsertgesCola]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesCola]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesCola]
	@CodFactura uniqueidentifier,
	@Factura int,
	@Pax int,
	@Mesa int,
	@Cliente varchar(100),
	@Fecha datetime,
	@Trabajador varchar(100),
	@Estado char(10),
	@Operacion char(20),
	@CodCola int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesCola] (
	[CodFactura],
	[Factura],
	[Pax],
	[Mesa],
	[Cliente],
	[Fecha],
	[Trabajador],
	[Estado],
	[Operacion]
) VALUES (
	@CodFactura,
	@Factura,
	@Pax,
	@Mesa,
	@Cliente,
	@Fecha,
	@Trabajador,
	@Estado,
	@Operacion
)

SET @CodCola = SCOPE_IDENTITY()

--endregion


