

--region [dbo].[pa_InsertUpdategesCobro]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesCobro]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesCobro]
	@CodCobro int,
	@Descripcion varchar(100),
	@Activo bit,
	@Devolucion bit,
	@Periodo int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodCobro] FROM [dbo].[gesCobro] WHERE [CodCobro] = @CodCobro)
BEGIN
	UPDATE [dbo].[gesCobro] SET
		[Descripcion] = @Descripcion,
		[Activo] = @Activo,
		[Devolucion] = @Devolucion,
		[Periodo] = @Periodo
	WHERE
		[CodCobro] = @CodCobro
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesCobro] (
		[CodCobro],
		[Descripcion],
		[Activo],
		[Devolucion],
		[Periodo]
	) VALUES (
		@CodCobro,
		@Descripcion,
		@Activo,
		@Devolucion,
		@Periodo
	)
END

--endregion


