

--region [dbo].[pa_InsertgesArticuloGrupo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesArticuloGrupo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesArticuloGrupo]
	@Descripcion char(50),
	@Activo bit,
	@CodGrupo int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesArticuloGrupo] (
	[Descripcion],
	[Activo]
) VALUES (
	@Descripcion,
	@Activo
)

SET @CodGrupo = SCOPE_IDENTITY()

--endregion


