

--region [dbo].[pa_InsertgesReserva]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesReserva]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesReserva]
	@Llegada datetime,
	@Reservada datetime,
	@Sentados datetime,
	@Realizada datetime,
	@Telefono1 char(12),
	@Telefono2 char(12),
	@CodCliente int,
	@Cliente char(250),
	@Pax char(10),
	@Observaciones char(355),
	@CodTrabajador int,
	@Trabajador char(150),
	@CodLocal int,
	@Centro char(150),
	@CodZona int,
	@Zona char(100),
	@Señal char(50),
	@CodReserva uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodReserva = NEWID()

INSERT INTO [dbo].[gesReservas] (
	[CodReserva],
	[Llegada],
	[Reservada],
	[Sentados],
	[Realizada],
	[Telefono1],
	[Telefono2],
	[CodCliente],
	[Cliente],
	[Pax],
	[Observaciones],
	[CodTrabajador],
	[Trabajador],
	[CodLocal],
	[Centro],
	[CodZona],
	[Zona],
	[Señal]
) VALUES (
	@CodReserva,
	@Llegada,
	@Reservada,
	@Sentados,
	@Realizada,
	@Telefono1,
	@Telefono2,
	@CodCliente,
	@Cliente,
	@Pax,
	@Observaciones,
	@CodTrabajador,
	@Trabajador,
	@CodLocal,
	@Centro,
	@CodZona,
	@Zona,
	@Señal
)

--endregion


