

--region [dbo].[pa_InsertgesEscandallo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesEscandallo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesEscandallo]
	@CodProducto uniqueidentifier,
	@CodClase int,
	@Clase varchar(100),
	@Cantidad decimal(18, 4),
	@CodMagnitud int,
	@CodEscandallo uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodEscandallo = NEWID()

INSERT INTO [dbo].[gesEscandallo] (
	[CodEscandallo],
	[CodProducto],
	[CodClase],
	[Clase],
	[Cantidad],
	[CodMagnitud]
) VALUES (
	@CodEscandallo,
	@CodProducto,
	@CodClase,
	@Clase,
	@Cantidad,
	@CodMagnitud
)

--endregion


