

--region [dbo].[pa_InsertTotalDetalleArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertTotalDetalleArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertTotalDetalleArqueo]
	@Fecha datetime,
	@Periodo nvarchar(50),
	@Detalle nvarchar(50),
	@Total decimal(18, 2),
	@Codigo bigint
AS

SET NOCOUNT ON

INSERT INTO [dbo].[TotalDetalleArqueo] (
	[Fecha],
	[Periodo],
	[Detalle],
	[Total],
	[Codigo]
) VALUES (
	@Fecha,
	@Periodo,
	@Detalle,
	@Total,
	@Codigo
)

--endregion
