

--region [dbo].[pa_InsertgesAnulacionTipo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesAnulacionTipo]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesAnulacionTipo]
	@Descripcion char(100),
	@Resta bit,
	@Activo bit,
	@CodTipo int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesAnulacionTipo] (
	[Descripcion],
	[Resta],
	[Activo]
) VALUES (
	@Descripcion,
	@Resta,
	@Activo
)

SET @CodTipo = SCOPE_IDENTITY()

--endregion


