

--region [dbo].[pa_InsertgesAnulacione]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesAnulacione]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesAnulacione]
	@CodAnulacion int,
	@CodTrabajador int,
	@Fecha datetime,
	@CodProducto int,
	@CodTipo int
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesAnulaciones] (
	[CodAnulacion],
	[CodTrabajador],
	[Fecha],
	[CodProducto],
	[CodTipo]
) VALUES (
	@CodAnulacion,
	@CodTrabajador,
	@Fecha,
	@CodProducto,
	@CodTipo
)

--endregion


