

--region [dbo].[pa_InsertUpdateTotalDetalleArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdateTotalDetalleArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdateTotalDetalleArqueo]
	@Fecha datetime,
	@Periodo nvarchar(50),
	@Detalle nvarchar(50),
	@Total decimal(18, 2),
	@Codigo bigint
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Fecha], [Periodo], [Detalle], [Codigo] FROM [dbo].[TotalDetalleArqueo] WHERE [Fecha] = @Fecha AND [Periodo] = @Periodo AND [Detalle] = @Detalle AND [Codigo] = @Codigo)
BEGIN
	UPDATE [dbo].[TotalDetalleArqueo] SET
		[Total] = @Total
	WHERE
		[Fecha] = @Fecha
		AND [Periodo] = @Periodo
		AND [Detalle] = @Detalle
		AND [Codigo] = @Codigo
END
ELSE
BEGIN
	INSERT INTO [dbo].[TotalDetalleArqueo] (
		[Fecha],
		[Periodo],
		[Detalle],
		[Total],
                           [Codigo]
	) VALUES (
		@Fecha,
		@Periodo,
		@Detalle,
		@Total,
                           @Codigo
	)
END

--endregion