

--region [dbo].[pa_InsertgesEnvase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesEnvase]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesEnvase]
	@CodEnvase int,
	@Descripcion char(50),
	@Activo bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesEnvase] (
	[CodEnvase],
	[Descripcion],
	[Activo]
) VALUES (
	@CodEnvase,
	@Descripcion,
	@Activo
)

--endregion


