

--region [dbo].[pa_InsertUpdategesEstatu]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesEstatu]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesEstatu]
	@CodEstatus int,
	@Descripcion varchar(50),
	@Activo bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodEstatus] FROM [dbo].[gesEstatus] WHERE [CodEstatus] = @CodEstatus)
BEGIN
	UPDATE [dbo].[gesEstatus] SET
		[Descripcion] = @Descripcion,
		[Activo] = @Activo
	WHERE
		[CodEstatus] = @CodEstatus
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesEstatus] (
		[CodEstatus],
		[Descripcion],
		[Activo]
	) VALUES (
		@CodEstatus,
		@Descripcion,
		@Activo
	)
END

--endregion


