

--region [dbo].[pa_InsertUpdategesMesa]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesMesa]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesMesa]
	@CodMesa int,
	@Mesa int,
	@Pax int,
	@Activa bit,
	@CodZona int,
	@CodLocal int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodMesa] FROM [dbo].[gesMesa] WHERE [CodMesa] = @CodMesa)
BEGIN
	UPDATE [dbo].[gesMesa] SET
		[Mesa] = @Mesa,
		[Pax] = @Pax,
		[Activa] = @Activa,
		[CodZona] = @CodZona,
		[CodLocal] = @CodLocal
	WHERE
		[CodMesa] = @CodMesa
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesMesa] (
		[CodMesa],
		[Mesa],
		[Pax],
		[Activa],
		[CodZona],
		[CodLocal]
	) VALUES (
		@CodMesa,
		@Mesa,
		@Pax,
		@Activa,
		@CodZona,
		@CodLocal
	)
END

--endregion


