

--region [dbo].[pa_InsertgesMagnitud]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesMagnitud]
-- Date Generated: viernes, 01 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesMagnitud]
	@Descripcion varchar(100),
	@Conversion decimal(18, 4),
	@Tipo char(10),
	@CodMagnitud int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesMagnitud] (
	[Descripcion],
	[Conversion],
	[Tipo]
) VALUES (
	@Descripcion,
	@Conversion,
	@Tipo
)

SET @CodMagnitud = SCOPE_IDENTITY()

--endregion


