

--region [dbo].[pa_InsertUpdategesProducto]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesProducto]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesProducto]
	@CodProducto uniqueidentifier,
	@CodGrupo int,
	@CodFamilia int,
	@CodZona int,
	@Descripcion varchar(100),
	@Activo bit,
	@Precio decimal(18, 2)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodProducto] FROM [dbo].[gesProducto] WHERE [CodProducto] = @CodProducto)
BEGIN
	UPDATE [dbo].[gesProducto] SET
		[CodGrupo] = @CodGrupo,
		[CodFamilia] = @CodFamilia,
		[CodZona] = @CodZona,
		[Descripcion] = @Descripcion,
		[Activo] = @Activo,
		[Precio] = @Precio
	WHERE
		[CodProducto] = @CodProducto
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesProducto] (
		[CodProducto],
		[CodGrupo],
		[CodFamilia],
		[CodZona],
		[Descripcion],
		[Activo],
		[Precio]
	) VALUES (
		@CodProducto,
		@CodGrupo,
		@CodFamilia,
		@CodZona,
		@Descripcion,
		@Activo,
		@Precio
	)
END

--endregion


