

--region [dbo].[pa_InsertgesArqueoDetalle]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesArqueoDetalle]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesArqueoDetalle]
	@CodArqueo uniqueidentifier,
	@Realidad varchar(100),
	@Contado decimal(18, 2),
	@Registro varchar(100),
	@Vendido decimal(18, 2),
	@Diferencia decimal(18, 2),
	@Periodo int,
	@CodDetalle uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodDetalle = NEWID()

INSERT INTO [dbo].[gesArqueoDetalle] (
	[CodDetalle],
	[CodArqueo],
	[Realidad],
	[Contado],
	[Registro],
	[Vendido],
	[Diferencia],
	[Periodo]
) VALUES (
	@CodDetalle,
	@CodArqueo,
	@Realidad,
	@Contado,
	@Registro,
	@Vendido,
	@Diferencia,
	@Periodo
)

--endregion


