

--region [dbo].[pa_InsertUpdategesZona]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesZona]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesZona]
	@CodZona int,
	@CodLocal int,
	@CodDispositivo int,
	@CodActividad int,
	@Nombre varchar(100),
	@Activa bit,
	@Tipo char(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodZona] FROM [dbo].[gesZonas] WHERE [CodZona] = @CodZona)
BEGIN
	UPDATE [dbo].[gesZonas] SET
		[CodLocal] = @CodLocal,
		[CodDispositivo] = @CodDispositivo,
		[CodActividad] = @CodActividad,
		[Nombre] = @Nombre,
		[Activa] = @Activa,
		[Tipo] = @Tipo
	WHERE
		[CodZona] = @CodZona
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesZonas] (
		[CodZona],
		[CodLocal],
		[CodDispositivo],
		[CodActividad],
		[Nombre],
		[Activa],
		[Tipo]
	) VALUES (
		@CodZona,
		@CodLocal,
		@CodDispositivo,
		@CodActividad,
		@Nombre,
		@Activa,
		@Tipo
	)
END

--endregion


