

--region [dbo].[pa_InsertUpdategesProducto_Num]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesProducto_Num]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesProducto_Num]
	@CodProducto uniqueidentifier,
	@CodGrupo int,
	@CodFamilia int,
	@CodZona int,
	@CodProducto_Num int,
	@Descripcion varchar(100),
	@Activo bit,
	@Precio decimal(18, 2),
	@ConEscandallo bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodProducto_Num] FROM [dbo].[gesProducto_Num] WHERE [CodProducto_Num] = @CodProducto_Num)
BEGIN
	UPDATE [dbo].[gesProducto_Num] SET
		[CodProducto] = @CodProducto,
		[CodGrupo] = @CodGrupo,
		[CodFamilia] = @CodFamilia,
		[CodZona] = @CodZona,
		[Descripcion] = @Descripcion,
		[Activo] = @Activo,
		[Precio] = @Precio,
		[ConEscandallo] = @ConEscandallo
	WHERE
		[CodProducto_Num] = @CodProducto_Num
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesProducto_Num] (
		[CodProducto],
		[CodGrupo],
		[CodFamilia],
		[CodZona],
		[CodProducto_Num],
		[Descripcion],
		[Activo],
		[Precio],
		[ConEscandallo]
	) VALUES (
		@CodProducto,
		@CodGrupo,
		@CodFamilia,
		@CodZona,
		@CodProducto_Num,
		@Descripcion,
		@Activo,
		@Precio,
		@ConEscandallo
	)
END

--endregion


