

--region [dbo].[pa_InsertgesPedidoDetalle]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesPedidoDetalle]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesPedidoDetalle]
	@CodPedido uniqueidentifier,
	@CodArticulo int,
	@CodCatalogo int,
	@Debe_haber decimal(18, 4),
	@Tenemos decimal(18, 4),
	@Pedimos decimal(18, 4),
	@Pedido datetime,
	@PresentacionUnidades decimal(18, 4),
	@PresentacionPrecio decimal(18, 4),
	@PresentacionFormatoPedido nvarchar(100),
	@PresentacionFormatoEnvase nvarchar(100),
	@PresentacionFormatoEmpaquetado nvarchar(100),
	@Recibido datetime,
	@Recibi bit,
	@Pedido_por varchar(50),
	@Recibido_por varchar(50),
	@Precio decimal(18, 4),
	@Subtotal decimal(18, 2),
	@Descuento decimal(18, 4),
	@IVA decimal(18, 2),
	@Observaciones nvarchar(200),
	@Cajas decimal(18, 4),
	@CodDetalle uniqueidentifier OUTPUT
AS

SET NOCOUNT ON

SET @CodDetalle = NEWID()

INSERT INTO [dbo].[gesPedidoDetalle] (
	[CodDetalle],
	[CodPedido],
	[CodArticulo],
	[CodCatalogo],
	[Debe_haber],
	[Tenemos],
	[Pedimos],
	[Pedido],
	[PresentacionUnidades],
	[PresentacionPrecio],
	[PresentacionFormatoPedido],
	[PresentacionFormatoEnvase],
	[PresentacionFormatoEmpaquetado],
	[Recibido],
	[Recibi],
	[Pedido_por],
	[Recibido_por],
	[Precio],
	[Subtotal],
	[Descuento],
	[IVA],
	[Observaciones],
	[Cajas]
) VALUES (
	@CodDetalle,
	@CodPedido,
	@CodArticulo,
	@CodCatalogo,
	@Debe_haber,
	@Tenemos,
	@Pedimos,
	@Pedido,
	@PresentacionUnidades,
	@PresentacionPrecio,
	@PresentacionFormatoPedido,
	@PresentacionFormatoEnvase,
	@PresentacionFormatoEmpaquetado,
	@Recibido,
	@Recibi,
	@Pedido_por,
	@Recibido_por,
	@Precio,
	@Subtotal,
	@Descuento,
	@IVA,
	@Observaciones,
	@Cajas
)

--endregion


