

--region [dbo].[pa_InsertUpdategesFacTique]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesFacTique]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesFacTique]
	@CodDetalle uniqueidentifier,
	@CodFactura uniqueidentifier,
	@CodProducto uniqueidentifier,
	@Detalle varchar(150),
	@Unidad int,
	@Importe decimal(18, 2),
	@SubTotal decimal(18, 2),
	@CodTrabajador int,
	@Suceso char(50),
	@Operacion char(50),
	@Fecha datetime,
	@Orden int,
	@CodDispositivo int,
	@Dispositivo char(50),
	@Actividad varchar(100),
	@CodZona int,
	@Zona varchar(100),
	@CodGrupo int,
	@Grupo varchar(100),
	@CodFamilia int,
	@Familia varchar(100),
	@CodActividad int,
	@Mesa int,
	@Cliente varchar(100),
	@Trabajador varchar(100),
	@CodPeriodo int,
	@Periodo char(50),
	@Activo bit,
	@Relacion uniqueidentifier,
	@Estadio char(50),
	@CodCola int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodDetalle] FROM [dbo].[gesFacTique] WHERE [CodDetalle] = @CodDetalle)
BEGIN
	UPDATE [dbo].[gesFacTique] SET
		[CodFactura] = @CodFactura,
		[CodProducto] = @CodProducto,
		[Detalle] = @Detalle,
		[Unidad] = @Unidad,
		[Importe] = @Importe,
		[SubTotal] = @SubTotal,
		[CodTrabajador] = @CodTrabajador,
		[Suceso] = @Suceso,
		[Operacion] = @Operacion,
		[Fecha] = @Fecha,
		[CodDispositivo] = @CodDispositivo,
		[Dispositivo] = @Dispositivo,
		[Actividad] = @Actividad,
		[CodZona] = @CodZona,
		[Zona] = @Zona,
		[CodGrupo] = @CodGrupo,
		[Grupo] = @Grupo,
		[CodFamilia] = @CodFamilia,
		[Familia] = @Familia,
		[CodActividad] = @CodActividad,
		[Mesa] = @Mesa,
		[Cliente] = @Cliente,
		[Trabajador] = @Trabajador,
		[CodPeriodo] = @CodPeriodo,
		[Periodo] = @Periodo,
		[Activo] = @Activo,
		[Relacion] = @Relacion,
		[Estadio] = @Estadio,
		[CodCola] = @CodCola
	WHERE
		[CodDetalle] = @CodDetalle
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesFacTique] (
		[CodDetalle],
		[CodFactura],
		[CodProducto],
		[Detalle],
		[Unidad],
		[Importe],
		[SubTotal],
		[CodTrabajador],
		[Suceso],
		[Operacion],
		[Fecha],
		[CodDispositivo],
		[Dispositivo],
		[Actividad],
		[CodZona],
		[Zona],
		[CodGrupo],
		[Grupo],
		[CodFamilia],
		[Familia],
		[CodActividad],
		[Mesa],
		[Cliente],
		[Trabajador],
		[CodPeriodo],
		[Periodo],
		[Activo],
		[Relacion],
		[Estadio],
		[CodCola],
		[Orden]
	) VALUES (
		@CodDetalle,
		@CodFactura,
		@CodProducto,
		@Detalle,
		@Unidad,
		@Importe,
		@SubTotal,
		@CodTrabajador,
		@Suceso,
		@Operacion,
		@Fecha,
		@CodDispositivo,
		@Dispositivo,
		@Actividad,
		@CodZona,
		@Zona,
		@CodGrupo,
		@Grupo,
		@CodFamilia,
		@Familia,
		@CodActividad,
		@Mesa,
		@Cliente,
		@Trabajador,
		@CodPeriodo,
		@Periodo,
		@Activo,
		@Relacion,
		@Estadio,
		@CodCola,
		@Orden
	)
END

--endregion
