

--region [dbo].[pa_InsertGesArticuloClaseConEscandallo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertGesArticuloClaseConEscandallo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertGesArticuloClaseConEscandallo]
	@CodClaseHijo int,
	@CodClasePadre int,
	@Cantidad decimal(18, 4),
	@CodMagnitud int,
	@Codigo int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[GesArticuloClaseConEscandallo] (
	[CodClaseHijo],
	[CodClasePadre],
	[Cantidad],
	[CodMagnitud]
) VALUES (
	@CodClaseHijo,
	@CodClasePadre,
	@Cantidad,
	@CodMagnitud
)

SET @Codigo = SCOPE_IDENTITY()

--endregion


