

--region [dbo].[pa_InsertUpdategesArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesArqueo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesArqueo]
	@CodArqueo uniqueidentifier,
	@Orden int,
	@Fecha datetime,
	@CodTrabajador int,
	@Trabajador varchar(150),
	@CodLocal int,
	@Centro varchar(100),
	@CodDispositivo int,
	@Dispositivo varchar(100),
	@Comprobado bit,
	@Dia datetime,
	@CodPeriodo int,
	@Periodo char(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodArqueo] FROM [dbo].[gesArqueo] WHERE [CodArqueo] = @CodArqueo)
BEGIN
	UPDATE [dbo].[gesArqueo] SET
		[Fecha] = @Fecha,
		[CodTrabajador] = @CodTrabajador,
		[Trabajador] = @Trabajador,
		[CodLocal] = @CodLocal,
		[Centro] = @Centro,
		[CodDispositivo] = @CodDispositivo,
		[Dispositivo] = @Dispositivo,
		[Comprobado] = @Comprobado,
		[Dia] = @Dia,
		[CodPeriodo] = @CodPeriodo,
		[Periodo] = @Periodo
	WHERE
		[CodArqueo] = @CodArqueo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesArqueo] (
		[CodArqueo],
		[Fecha],
		[CodTrabajador],
		[Trabajador],
		[CodLocal],
		[Centro],
		[CodDispositivo],
		[Dispositivo],
		[Comprobado],
		[Dia],
		[CodPeriodo],
		[Periodo]
	) VALUES (
		@CodArqueo,
		@Fecha,
		@CodTrabajador,
		@Trabajador,
		@CodLocal,
		@Centro,
		@CodDispositivo,
		@Dispositivo,
		@Comprobado,
		@Dia,
		@CodPeriodo,
		@Periodo
	)
END

--endregion
