

--region [dbo].[pa_InsertUpdategesProveedore]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesProveedore]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesProveedore]
	@CodProveedor int,
	@Nombre char(30),
	@Apellidos char(30),
	@Empresa char(30),
	@TelefonoFijo char(15),
	@TelefonoMovil char(15),
	@Cif char(20),
	@Direccion char(20),
	@Localidad char(15),
	@Provincia char(15),
	@Activo bit,
	@Email char(50),
	@TipoPago char(15),
	@NRSanitario char(150)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodProveedor] FROM [dbo].[gesProveedores] WHERE [CodProveedor] = @CodProveedor)
BEGIN
	UPDATE [dbo].[gesProveedores] SET
		[Nombre] = @Nombre,
		[Apellidos] = @Apellidos,
		[Empresa] = @Empresa,
		[TelefonoFijo] = @TelefonoFijo,
		[TelefonoMovil] = @TelefonoMovil,
		[Cif] = @Cif,
		[Direccion] = @Direccion,
		[Localidad] = @Localidad,
		[Provincia] = @Provincia,
		[Activo] = @Activo,
		[Email] = @Email,
		[TipoPago] = @TipoPago,
		[NRSanitario] = @NRSanitario
	WHERE
		[CodProveedor] = @CodProveedor
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesProveedores] (
		[CodProveedor],
		[Nombre],
		[Apellidos],
		[Empresa],
		[TelefonoFijo],
		[TelefonoMovil],
		[Cif],
		[Direccion],
		[Localidad],
		[Provincia],
		[Activo],
		[Email],
		[TipoPago],
		[NRSanitario]
	) VALUES (
		@CodProveedor,
		@Nombre,
		@Apellidos,
		@Empresa,
		@TelefonoFijo,
		@TelefonoMovil,
		@Cif,
		@Direccion,
		@Localidad,
		@Provincia,
		@Activo,
		@Email,
		@TipoPago,
		@NRSanitario
	)
END

--endregion


