

--region [dbo].[pa_InsertUpdategesArticuloClase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesArticuloClase]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesArticuloClase]
	@CodClase int,
	@Descripcion varchar(100),
	@Activo bit,
	@ConEscandallo bit,
	@Cantidad decimal(18, 4),
	@CodMagnitud int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodClase] FROM [dbo].[gesArticuloClase] WHERE [CodClase] = @CodClase)
BEGIN
	UPDATE [dbo].[gesArticuloClase] SET
		[Descripcion] = @Descripcion,
		[Activo] = @Activo,
		[ConEscandallo] = @ConEscandallo,
		[Cantidad] = @Cantidad,
		[CodMagnitud] = @CodMagnitud
	WHERE
		[CodClase] = @CodClase
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesArticuloClase] (
		[CodClase],
		[Descripcion],
		[Activo],
		[ConEscandallo],
		[Cantidad],
		[CodMagnitud]
	) VALUES (
		@CodClase,
		@Descripcion,
		@Activo,
		@ConEscandallo,
		@Cantidad,
		@CodMagnitud
	)
END

--endregion


