

--region [dbo].[pa_InsertTotalArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertTotalArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertTotalArqueo]
	@Fecha datetime,
	@Total decimal(18, 2),
	@Codigo bigint OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[TotalArqueo] (
	[Fecha],
	[Total]
) VALUES (
	@Fecha,
	@Total
)

SET @Codigo = SCOPE_IDENTITY()

--endregion
