

--region [dbo].[pa_InsertgesCobro]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesCobro]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesCobro]
	@CodCobro int,
	@Descripcion varchar(100),
	@Activo bit,
	@Devolucion bit,
	@Periodo int
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesCobro] (
	[CodCobro],
	[Descripcion],
	[Activo],
	[Devolucion],
	[Periodo]
) VALUES (
	@CodCobro,
	@Descripcion,
	@Activo,
	@Devolucion,
	@Periodo
)

--endregion


