

--region [dbo].[pa_InsertgesArticuloClase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesArticuloClase]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesArticuloClase]
	@Descripcion varchar(100),
	@Activo bit,
	@ConEscandallo bit,
	@Cantidad decimal(18, 4),
	@CodMagnitud int,
	@CodClase int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesArticuloClase] (
	[Descripcion],
	[Activo],
	[ConEscandallo],
	[Cantidad],
	[CodMagnitud]
) VALUES (
	@Descripcion,
	@Activo,
	@ConEscandallo,
	@Cantidad,
	@CodMagnitud
)

SET @CodClase = SCOPE_IDENTITY()

--endregion


