

--region [dbo].[pa_InsertgesPoblacion]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesPoblacion]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesPoblacion]
	@CodPoblacion int,
	@Descripcion char(20)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesPoblacion] (
	[CodPoblacion],
	[Descripcion]
) VALUES (
	@CodPoblacion,
	@Descripcion
)

--endregion


