

--region [dbo].[pa_InsertUpdategesLocal]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesLocal]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesLocal]
	@CodLocal int,
	@Nombre varchar(100),
	@Activo bit,
	@Direccion varchar(150),
	@Localidad varchar(50),
	@Provincia varchar(50),
	@CIF varchar(20),
	@Telefono char(20)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodLocal] FROM [dbo].[gesLocal] WHERE [CodLocal] = @CodLocal)
BEGIN
	UPDATE [dbo].[gesLocal] SET
		[Nombre] = @Nombre,
		[Activo] = @Activo,
		[Direccion] = @Direccion,
		[Localidad] = @Localidad,
		[Provincia] = @Provincia,
		[CIF] = @CIF,
		[Telefono] = @Telefono
	WHERE
		[CodLocal] = @CodLocal
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesLocal] (
		[CodLocal],
		[Nombre],
		[Activo],
		[Direccion],
		[Localidad],
		[Provincia],
		[CIF],
		[Telefono]
	) VALUES (
		@CodLocal,
		@Nombre,
		@Activo,
		@Direccion,
		@Localidad,
		@Provincia,
		@CIF,
		@Telefono
	)
END

--endregion


