

--region [dbo].[pa_InsertUpdategesArticuloGrupo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesArticuloGrupo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesArticuloGrupo]
	@CodGrupo int,
	@Descripcion char(50),
	@Activo bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodGrupo] FROM [dbo].[gesArticuloGrupo] WHERE [CodGrupo] = @CodGrupo)
BEGIN
	UPDATE [dbo].[gesArticuloGrupo] SET
		[Descripcion] = @Descripcion,
		[Activo] = @Activo
	WHERE
		[CodGrupo] = @CodGrupo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesArticuloGrupo] (
		[CodGrupo],
		[Descripcion],
		[Activo]
	) VALUES (
		@CodGrupo,
		@Descripcion,
		@Activo
	)
END

--endregion


