

--region [dbo].[pa_InsertgesPagoForma]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesPagoForma]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesPagoForma]
	@CodPago int,
	@Descripcion char(100),
	@Activo bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesPagoForma] (
	[CodPago],
	[Descripcion],
	[Activo]
) VALUES (
	@CodPago,
	@Descripcion,
	@Activo
)

--endregion


