

--region [dbo].[pa_InsertUpdategesPeriodo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesPeriodo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesPeriodo]
	@CodPeriodo int,
	@Descripcion char(50),
	@Inicio datetime,
	@Final datetime
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodPeriodo] FROM [dbo].[gesPeriodos] WHERE [CodPeriodo] = @CodPeriodo)
BEGIN
	UPDATE [dbo].[gesPeriodos] SET
		[Descripcion] = @Descripcion,
		[Inicio] = @Inicio,
		[Final] = @Final
	WHERE
		[CodPeriodo] = @CodPeriodo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesPeriodos] (
		[CodPeriodo],
		[Descripcion],
		[Inicio],
		[Final]
	) VALUES (
		@CodPeriodo,
		@Descripcion,
		@Inicio,
		@Final
	)
END

--endregion


