

--region [dbo].[pa_InsertgesEstatu]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesEstatu]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesEstatu]
	@Descripcion varchar(50),
	@Activo bit,
	@CodEstatus int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesEstatus] (
	[Descripcion],
	[Activo]
) VALUES (
	@Descripcion,
	@Activo
)

SET @CodEstatus = SCOPE_IDENTITY()

--endregion


