

--region [dbo].[pa_InsertgesLocal]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesLocal]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesLocal]
	@CodLocal int,
	@Nombre varchar(100),
	@Activo bit,
	@Direccion varchar(150),
	@Localidad varchar(50),
	@Provincia varchar(50),
	@CIF varchar(20),
	@Telefono char(20)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesLocal] (
	[CodLocal],
	[Nombre],
	[Activo],
	[Direccion],
	[Localidad],
	[Provincia],
	[CIF],
	[Telefono]
) VALUES (
	@CodLocal,
	@Nombre,
	@Activo,
	@Direccion,
	@Localidad,
	@Provincia,
	@CIF,
	@Telefono
)

--endregion


