

--region [dbo].[pa_InsertgesPeriodo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesPeriodo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesPeriodo]
	@Descripcion char(50),
	@Inicio datetime,
	@Final datetime,
	@CodPeriodo int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesPeriodos] (
	[Descripcion],
	[Inicio],
	[Final]
) VALUES (
	@Descripcion,
	@Inicio,
	@Final
)

SET @CodPeriodo = SCOPE_IDENTITY()

--endregion


