

--region [dbo].[pa_InsertgesCatalogo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertgesCatalogo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertgesCatalogo]
	@CodProveedor int,
	@CodArticulo int,
	@CodFormatoPedido int,
	@CodEmpaquetado int,
	@Precio decimal(18, 4),
	@Pedir bit,
	@IVA decimal(18, 2),
	@Debe_haber decimal(18, 2),
	@Importe decimal(18, 4),
	@Contenido_unidad decimal(18, 2),
	@Contenido_caja decimal(18, 2),
	@PedirCajas bit,
	@Preferente bit,
	@PrecioUltimoCompra decimal(18, 2),
	@PrecioMedioCompra decimal(18, 2),
	@CodCatalogo int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[gesCatalogo] (
	[CodProveedor],
	[CodArticulo],
	[CodFormatoPedido],
	[CodEmpaquetado],
	[Precio],
	[Pedir],
	[IVA],
	[Debe_haber],
	[Importe],
	[Contenido_unidad],
	[Contenido_caja],
	[PedirCajas],
	[Preferente],
	[PrecioUltimoCompra],
	[PrecioMedioCompra]
) VALUES (
	@CodProveedor,
	@CodArticulo,
	@CodFormatoPedido,
	@CodEmpaquetado,
	@Precio,
	@Pedir,
	@IVA,
	@Debe_haber,
	@Importe,
	@Contenido_unidad,
	@Contenido_caja,
	@PedirCajas,
	@Preferente,
	@PrecioUltimoCompra,
	@PrecioMedioCompra
)

SET @CodCatalogo = SCOPE_IDENTITY()

--endregion


