

--region [dbo].[pa_InsertUpdategesFichaje]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesFichaje]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesFichaje]
	@CodFichaje uniqueidentifier,
	@CodTrabajador int,
	@Nombre varchar(100),
	@Apellidos varchar(100),
	@Entrada datetime,
	@Salida datetime,
	@CodPeriodo int,
	@Periodo char(50),
	@CodLocal int,
	@Centro varchar(100),
	@CodZona int,
	@Zona varchar(100),
	@CodDispositivo int,
	@Estado char(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodFichaje] FROM [dbo].[gesFichaje] WHERE [CodFichaje] = @CodFichaje)
BEGIN
	UPDATE [dbo].[gesFichaje] SET
		[CodTrabajador] = @CodTrabajador,
		[Nombre] = @Nombre,
		[Apellidos] = @Apellidos,
		[Entrada] = @Entrada,
		[Salida] = @Salida,
		[CodPeriodo] = @CodPeriodo,
		[Periodo] = @Periodo,
		[CodLocal] = @CodLocal,
		[Centro] = @Centro,
		[CodZona] = @CodZona,
		[Zona] = @Zona,
		[CodDispositivo] = @CodDispositivo,
		[Estado] = @Estado
	WHERE
		[CodFichaje] = @CodFichaje
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesFichaje] (
		[CodFichaje],
		[CodTrabajador],
		[Nombre],
		[Apellidos],
		[Entrada],
		[Salida],
		[CodPeriodo],
		[Periodo],
		[CodLocal],
		[Centro],
		[CodZona],
		[Zona],
		[CodDispositivo],
		[Estado]
	) VALUES (
		@CodFichaje,
		@CodTrabajador,
		@Nombre,
		@Apellidos,
		@Entrada,
		@Salida,
		@CodPeriodo,
		@Periodo,
		@CodLocal,
		@Centro,
		@CodZona,
		@Zona,
		@CodDispositivo,
		@Estado
	)
END

--endregion


