

--region [dbo].[pa_InsertUpdategesEscandallo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_InsertUpdategesEscandallo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_InsertUpdategesEscandallo]
	@CodEscandallo uniqueidentifier,
	@CodProducto uniqueidentifier,
	@CodClase int,
	@Clase varchar(100),
	@Cantidad decimal(18, 4),
	@CodMagnitud int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [CodEscandallo] FROM [dbo].[gesEscandallo] WHERE [CodEscandallo] = @CodEscandallo)
BEGIN
	UPDATE [dbo].[gesEscandallo] SET
		[CodProducto] = @CodProducto,
		[CodClase] = @CodClase,
		[Clase] = @Clase,
		[Cantidad] = @Cantidad,
		[CodMagnitud] = @CodMagnitud
	WHERE
		[CodEscandallo] = @CodEscandallo
END
ELSE
BEGIN
	INSERT INTO [dbo].[gesEscandallo] (
		[CodEscandallo],
		[CodProducto],
		[CodClase],
		[Clase],
		[Cantidad],
		[CodMagnitud]
	) VALUES (
		@CodEscandallo,
		@CodProducto,
		@CodClase,
		@Clase,
		@Cantidad,
		@CodMagnitud
	)
END

--endregion


