

--region [dbo].[pa_SelectgesMesa]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesMesa]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesMesa]
	@CodMesa int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodMesa],
	[Mesa],
	[Pax],
	[Activa],
	[CodZona],
	[CodLocal]
FROM
	[dbo].[gesMesa]
WHERE
	[CodMesa] = @CodMesa

--endregion


