

--region [dbo].[pa_SelectgesArqueosAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArqueosAll]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArqueosAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodArqueo],
	[Orden],
	[Fecha],
	[CodTrabajador],
	[Trabajador],
	[CodLocal],
	[Centro],
	[CodDispositivo],
	[Dispositivo],
	[Comprobado],
	[Dia],
	[CodPeriodo],
	[Periodo]
FROM
	[dbo].[gesArqueo]

--endregion


