

--region [dbo].[pa_SelectgesTrabajadorsByClave]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesTrabajadorsByClave]
-- Date Generated: lunes, 04 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesTrabajadorsByClave]
	@Clave char(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodTrabajador],
	[Nombre],
	[Apellidos],
	[Alias],
	[Activo],
	[Fijo],
	[Movil],
	[Direccion],
	[Localidad],
	[Provincia],
	[CP],
	[DNI],
	[SS],
	[Banco],
	[Clave],
	[CodEstatus],
	[CodSeguridad]
FROM
	[dbo].[gesTrabajador]
WHERE
	[Clave] = @Clave

--endregion


