

--region [dbo].[pa_SelectgesEscandallosByCodProducto]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesEscandallosByCodProducto]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesEscandallosByCodProducto]
	@CodProducto uniqueidentifier
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodEscandallo],
	[CodProducto],
	[CodClase],
	[Clase],
	[Cantidad],
	[CodMagnitud]
FROM
	[dbo].[gesEscandallo]
WHERE
	[CodProducto] = @CodProducto

--endregion


