

--region [dbo].[pa_SelectgesReservasDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesReservasDynamic]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesReservasDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[CodReserva],
	[Llegada],
	[Reservada],
	[Sentados],
	[Realizada],
	[Telefono1],
	[Telefono2],
	[CodCliente],
	[Cliente],
	[Pax],
	[Observaciones],
	[CodTrabajador],
	[Trabajador],
	[CodLocal],
	[Centro],
	[CodZona],
	[Zona],
	[Señal]
FROM
	[dbo].[gesReservas]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion


