

--region [dbo].[pa_SelectgesDispositivo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesDispositivo]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesDispositivo]
	@CodDispositivo int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodDispositivo],
	[Nombre],
	[Activo],
	[Tipo],
	[Imprime_comanda],
	[Imprime_tique],
	[Imprime_factura],
	[Abre_cajon]
FROM
	[dbo].[gesDispositivo]
WHERE
	[CodDispositivo] = @CodDispositivo

--endregion


