

--region [dbo].[pa_SelectgesLocalsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesLocalsAll]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesLocalsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodLocal],
	[Nombre],
	[Activo],
	[Direccion],
	[Localidad],
	[Provincia],
	[CIF],
	[Telefono]
FROM
	[dbo].[gesLocal]

--endregion


