

--region [dbo].[pa_SelectgesAnulacionesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesAnulacionesAll]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesAnulacionesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodAnulacion],
	[CodTrabajador],
	[Fecha],
	[CodProducto],
	[CodTipo]
FROM
	[dbo].[gesAnulaciones]

--endregion


