

--region [dbo].[pa_SelectgesFichaje]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesFichaje]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesFichaje]
	@CodFichaje uniqueidentifier
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodFichaje],
	[CodTrabajador],
	[Nombre],
	[Apellidos],
	[Entrada],
	[Salida],
	[CodPeriodo],
	[Periodo],
	[CodLocal],
	[Centro],
	[CodZona],
	[Zona],
	[CodDispositivo],
	[Estado]
FROM
	[dbo].[gesFichaje]
WHERE
	[CodFichaje] = @CodFichaje

--endregion


