

--region [dbo].[pa_SelectgesFacturasByMesaAndClienteAndEstado]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesFacturasByMesaAndClienteAndEstado]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesFacturasByMesaAndClienteAndEstado]
	@Mesa char(50),
	@Cliente varchar(100),
	@Estado varchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodFactura],
	[Abierta],
	[Facturada],
	[Cobrada],
	[Importe],
	[Mesa],
	[Pax],
	[CodCliente],
	[CodTrabajador],
	[Estado],
	[CodLocal],
	[Numero],
	[Cliente],
	[CodPeriodo],
	[Periodo],
	[Operador],
	[Dispositivo]
FROM
	[dbo].[gesFactura]
WHERE
	[Mesa] = @Mesa
	AND [Cliente] = @Cliente
	AND [Estado] = @Estado

--endregion


