

--region [dbo].[pa_SelectgesArticuloClase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArticuloClase]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArticuloClase]
	@CodClase int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodClase],
	[Descripcion],
	[Activo],
	[ConEscandallo],
	[Cantidad],
	[CodMagnitud]
FROM
	[dbo].[gesArticuloClase]
WHERE
	[CodClase] = @CodClase

--endregion


