
--region [dbo].[pa_SelectgesPedidosDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesPedidosDynamic]
-- Date Generated: miércoles, 19 de octubre de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesPedidosDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[CodPedido],
	[CodProveedor],
	[CodTrabajador],
	[Pedido],
	[Recibido],
	[Facturado],
	[Pagado],
	[Telefono],
	[Orden],
	[Albaran],
	[Factura],
	[Forma_pago],
	[Total_pedido],
	[Total_recibido],
	[Total_pagado],
	[Total],
	[CodFormaPago],
	[Observacion],
	[FechaCreacion],
	[CodTipoPedido]
FROM
	[dbo].[gesPedido]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

