

--region [dbo].[pa_SelectgesArticulo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArticulo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArticulo]
	@CodArticulo int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodArticulo],
	[CodGrupo],
	[CodFamilia],
	[CodEnvase],
	[CodMagnitud],
	[CodGrupoCompra],
	[CodSectorPedido],
	[CodClase],
	[Descripcion],
	[Activo],
	[Contenido_unidad],
	[Contenido_caja],
	[Existencias],
	[Debe_haber],
	[PrecioUltimoCompra],
	[PrecioMedioCompra]
FROM
	[dbo].[gesArticulo]
WHERE
	[CodArticulo] = @CodArticulo

--endregion


