

--region [dbo].[pa_SelectTotalArqueosByFecha]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectTotalArqueosByFecha]
-- Date Generated: viernes, 19 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectTotalArqueosByFecha]
	@Fecha datetime
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Fecha],
	[Total],
	[Codigo]
FROM
	[dbo].[TotalArqueo]
WHERE
	[Fecha] = @Fecha

--endregion


