
--region [dbo].[pa_SelectgesPedidosByCodTipoPedido]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesPedidosByCodTipoPedido]
-- Date Generated: miércoles, 19 de octubre de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesPedidosByCodTipoPedido]
	@CodTipoPedido int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodPedido],
	[CodProveedor],
	[CodTrabajador],
	[Pedido],
	[Recibido],
	[Facturado],
	[Pagado],
	[Telefono],
	[Orden],
	[Albaran],
	[Factura],
	[Forma_pago],
	[Total_pedido],
	[Total_recibido],
	[Total_pagado],
	[Total],
	[CodFormaPago],
	[Observacion],
	[FechaCreacion],
	[CodTipoPedido]
FROM
	[dbo].[gesPedido]
WHERE
	[CodTipoPedido] = @CodTipoPedido

--endregion

