

--region [dbo].[pa_SelectgesArqueoDetallesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArqueoDetallesAll]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArqueoDetallesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodDetalle],
	[CodArqueo],
	[Realidad],
	[Contado],
	[Registro],
	[Vendido],
	[Diferencia],
	[Periodo]
FROM
	[dbo].[gesArqueoDetalle]

--endregion


