

--region [dbo].[pa_SelectgesMagnitud]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesMagnitud]
-- Date Generated: viernes, 01 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesMagnitud]
	@CodMagnitud int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodMagnitud],
	[Descripcion],
	[Conversion],
	[Tipo]
FROM
	[dbo].[gesMagnitud]
WHERE
	[CodMagnitud] = @CodMagnitud

--endregion


