

--region [dbo].[pa_SelectgesProveedoresPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesProveedoresPaged]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesProveedoresPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodProveedor],
	[Nombre],
	[Apellidos],
	[Empresa],
	[TelefonoFijo],
	[TelefonoMovil],
	[Cif],
	[Direccion],
	[Localidad],
	[Provincia],
	[Activo],
	[Email],
	[TipoPago],
	[NRSanitario]
FROM
	[dbo].[gesProveedores]

--endregion


