

--region [dbo].[pa_SelectgesPedidosPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesPedidosPaged]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesPedidosPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodPedido],
	[CodProveedor],
	[CodTrabajador],
	[Pedido],
	[Recibido],
	[Facturado],
	[Pagado],
	[Telefono],
	[Orden],
	[Albaran],
	[Factura],
	[Forma_pago],
	[Total_pedido],
	[Total_recibido],
	[Total_pagado],
	[Total],
	[CodFormaPago],
	[Observacion],
	[FechaCreacion]
FROM
	[dbo].[gesPedido]

--endregion


