

--region [dbo].[pa_SelectgesArticuloClasesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArticuloClasesAll]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArticuloClasesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodClase],
	[Descripcion],
	[Activo],
	[ConEscandallo],
	[Cantidad],
	[CodMagnitud]
FROM
	[dbo].[gesArticuloClase]

--endregion


