

--region [dbo].[pa_SelectgesCatalogosByCodEmpaquetado]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesCatalogosByCodEmpaquetado]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesCatalogosByCodEmpaquetado]
	@CodEmpaquetado int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodCatalogo],
	[CodProveedor],
	[CodArticulo],
	[CodFormatoPedido],
	[CodEmpaquetado],
	[Precio],
	[Pedir],
	[IVA],
	[Debe_haber],
	[Importe],
	[Contenido_unidad],
	[Contenido_caja],
	[PedirCajas],
	[Preferente],
	[PrecioUltimoCompra],
	[PrecioMedioCompra]
FROM
	[dbo].[gesCatalogo]
WHERE
	[CodEmpaquetado] = @CodEmpaquetado

--endregion


