

--region [dbo].[pa_SelectgesSeguridad]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesSeguridad]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesSeguridad]
	@CodSeguridad int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodSeguridad],
	[Descripcion],
	[Activa]
FROM
	[dbo].[gesSeguridad]
WHERE
	[CodSeguridad] = @CodSeguridad

--endregion


