

--region [dbo].[pa_SelectgesEstatu]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesEstatu]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesEstatu]
	@CodEstatus int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodEstatus],
	[Descripcion],
	[Activo]
FROM
	[dbo].[gesEstatus]
WHERE
	[CodEstatus] = @CodEstatus

--endregion


