

--region [dbo].[pa_SelectgesClientesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesClientesAll]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesClientesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodCliente],
	[Nombre],
	[Apellidos],
	[Empresa],
	[Activo],
	[CIF],
	[Direccion],
	[Localidad],
	[Provincia],
	[CP],
	[CodClase],
	[Telefono1]
FROM
	[dbo].[gesCliente]

--endregion


