

--region [dbo].[pa_SelectgesProductosPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesProductosPaged]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesProductosPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodProducto],
	[CodGrupo],
	[CodFamilia],
	[CodZona],
	[Descripcion],
	[Activo],
	[Precio]
FROM
	[dbo].[gesProducto]

--endregion


