

--region [dbo].[pa_SelectgesAnulacione]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesAnulacione]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesAnulacione]
	@CodAnulacion int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodAnulacion],
	[CodTrabajador],
	[Fecha],
	[CodProducto],
	[CodTipo]
FROM
	[dbo].[gesAnulaciones]
WHERE
	[CodAnulacion] = @CodAnulacion

--endregion


