

--region [dbo].[pa_SelectTotalDetalleArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectTotalDetalleArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectTotalDetalleArqueo]
	@Fecha datetime,
	@Periodo nvarchar(50),
	@Detalle nvarchar(50),
	@Codigo bigint
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Fecha],
	[Periodo],
	[Detalle],
	[Total],
	[Codigo]
FROM
	[dbo].[TotalDetalleArqueo]
WHERE
	[Fecha] = @Fecha
	AND [Periodo] = @Periodo
	AND [Detalle] = @Detalle
	AND [Codigo] = @Codigo

--endregion


