

--region [dbo].[pa_SelectgesArqueoDetalle]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArqueoDetalle]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArqueoDetalle]
	@CodDetalle uniqueidentifier
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodDetalle],
	[CodArqueo],
	[Realidad],
	[Contado],
	[Registro],
	[Vendido],
	[Diferencia],
	[Periodo]
FROM
	[dbo].[gesArqueoDetalle]
WHERE
	[CodDetalle] = @CodDetalle

--endregion


