

--region [dbo].[pa_SelectTotalDetalleArqueosAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectTotalDetalleArqueosAll]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectTotalDetalleArqueosAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Fecha],
	[Periodo],
	[Detalle],
	[Total],
	[Codigo]
FROM
	[dbo].[TotalDetalleArqueo]

--endregion


