

--region [dbo].[pa_SelectgesCobro]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesCobro]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesCobro]
	@CodCobro int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodCobro],
	[Descripcion],
	[Activo],
	[Devolucion],
	[Periodo]
FROM
	[dbo].[gesCobro]
WHERE
	[CodCobro] = @CodCobro

--endregion


