

--region [dbo].[pa_SelectgesFamiliasPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesFamiliasPaged]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesFamiliasPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodFamilia],
	[Descripcion],
	[CodGrupo],
	[Activa],
	[CodZona]
FROM
	[dbo].[gesFamilia]

--endregion


