

--region [dbo].[pa_SelectgesEscandallo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesEscandallo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesEscandallo]
	@CodEscandallo uniqueidentifier
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodEscandallo],
	[CodProducto],
	[CodClase],
	[Clase],
	[Cantidad],
	[CodMagnitud]
FROM
	[dbo].[gesEscandallo]
WHERE
	[CodEscandallo] = @CodEscandallo

--endregion


