

--region [dbo].[pa_SelectgesArticulosDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesArticulosDynamic]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesArticulosDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[CodArticulo],
	[CodGrupo],
	[CodFamilia],
	[CodEnvase],
	[CodMagnitud],
	[CodGrupoCompra],
	[CodSectorPedido],
	[CodClase],
	[Descripcion],
	[Activo],
	[Contenido_unidad],
	[Contenido_caja],
	[Existencias],
	[Debe_haber],
	[PrecioUltimoCompra],
	[PrecioMedioCompra]
FROM
	[dbo].[gesArticulo]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion


