

--region [dbo].[pa_SelectgesGrupo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesGrupo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesGrupo]
	@CodGrupo int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodGrupo],
	[Descripcion],
	[Activo]
FROM
	[dbo].[gesGrupo]
WHERE
	[CodGrupo] = @CodGrupo

--endregion


