

--region [dbo].[pa_SelectgesZonasByCodDispositivo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesZonasByCodDispositivo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesZonasByCodDispositivo]
	@CodDispositivo int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodZona],
	[CodLocal],
	[CodDispositivo],
	[CodActividad],
	[Nombre],
	[Activa],
	[Tipo]
FROM
	[dbo].[gesZonas]
WHERE
	[CodDispositivo] = @CodDispositivo

--endregion


