

--region [dbo].[pa_SelectGesArticuloClaseConEscandallosByCodClasePadre]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectGesArticuloClaseConEscandallosByCodClasePadre]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectGesArticuloClaseConEscandallosByCodClasePadre]
	@CodClasePadre int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodClaseHijo],
	[CodClasePadre],
	[Codigo],
	[Cantidad],
	[CodMagnitud]
FROM
	[dbo].[GesArticuloClaseConEscandallo]
WHERE
	[CodClasePadre] = @CodClasePadre

--endregion


