

--region [dbo].[pa_SelectGesArticuloClaseConEscandallosAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectGesArticuloClaseConEscandallosAll]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectGesArticuloClaseConEscandallosAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodClaseHijo],
	[CodClasePadre],
	[Codigo],
	[Cantidad],
	[CodMagnitud]
FROM
	[dbo].[GesArticuloClaseConEscandallo]

--endregion


