

--region [dbo].[pa_SelectgesCaja]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesCaja]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesCaja]
	@CodCaja int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodCaja],
	[CodFactura],
	[CodCobro],
	[Entrega],
	[CodTrabajador]
FROM
	[dbo].[gesCaja]
WHERE
	[CodCaja] = @CodCaja

--endregion


