

--region [dbo].[pa_SelectgesAnulacionTipo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesAnulacionTipo]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesAnulacionTipo]
	@CodTipo int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodTipo],
	[Descripcion],
	[Resta],
	[Activo]
FROM
	[dbo].[gesAnulacionTipo]
WHERE
	[CodTipo] = @CodTipo

--endregion


