

--region [dbo].[pa_SelectTotalDetalleArqueosByFecha]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectTotalDetalleArqueosByFecha]
-- Date Generated: viernes, 19 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectTotalDetalleArqueosByFecha]
	@Fecha datetime
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Fecha],
	[Periodo],
	[Detalle],
	[Total],
	[Codigo],
	[Activo]
FROM
	[dbo].[TotalDetalleArqueo]
WHERE
	[Fecha] = @Fecha

--endregion


