

--region [dbo].[pa_SelectgesActividade]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesActividade]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesActividade]
	@CodActividad int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodActividad],
	[Descripcion],
	[Activa]
FROM
	[dbo].[gesActividades]
WHERE
	[CodActividad] = @CodActividad

--endregion


