

--region [dbo].[pa_SelectgesProducto_NumsByCodFamilia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_SelectgesProducto_NumsByCodFamilia]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_SelectgesProducto_NumsByCodFamilia]
	@CodFamilia int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[CodProducto],
	[CodGrupo],
	[CodFamilia],
	[CodZona],
	[CodProducto_Num],
	[Descripcion],
	[Activo],
	[Precio],
	[ConEscandallo]
FROM
	[dbo].[gesProducto_Num]
WHERE
	[CodFamilia] = @CodFamilia

--endregion


