

--region [dbo].[pa_UpdategesEnvase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesEnvase]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesEnvase]
	@CodEnvase int,
	@Descripcion char(50),
	@Activo bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesEnvase] SET
	[Descripcion] = @Descripcion,
	[Activo] = @Activo
WHERE
	[CodEnvase] = @CodEnvase

--endregion


