

--region [dbo].[pa_UpdategesMesa]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesMesa]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesMesa]
	@CodMesa int,
	@Mesa int,
	@Pax int,
	@Activa bit,
	@CodZona int,
	@CodLocal int
AS

SET NOCOUNT ON

UPDATE [dbo].[gesMesa] SET
	[Mesa] = @Mesa,
	[Pax] = @Pax,
	[Activa] = @Activa,
	[CodZona] = @CodZona,
	[CodLocal] = @CodLocal
WHERE
	[CodMesa] = @CodMesa

--endregion


