

--region [dbo].[pa_UpdategesPagoForma]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesPagoForma]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesPagoForma]
	@CodPago int,
	@Descripcion char(100),
	@Activo bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesPagoForma] SET
	[Descripcion] = @Descripcion,
	[Activo] = @Activo
WHERE
	[CodPago] = @CodPago

--endregion


