

--region [dbo].[pa_UpdategesActividade]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesActividade]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesActividade]
	@CodActividad int,
	@Descripcion varchar(100),
	@Activa bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesActividades] SET
	[Descripcion] = @Descripcion,
	[Activa] = @Activa
WHERE
	[CodActividad] = @CodActividad

--endregion


