

--region [dbo].[pa_UpdategesPoblacion]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesPoblacion]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesPoblacion]
	@CodPoblacion int,
	@Descripcion char(20)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesPoblacion] SET
	[Descripcion] = @Descripcion
WHERE
	[CodPoblacion] = @CodPoblacion

--endregion


