

--region [dbo].[pa_UpdategesCobro]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesCobro]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesCobro]
	@CodCobro int,
	@Descripcion varchar(100),
	@Activo bit,
	@Devolucion bit,
	@Periodo int
AS

SET NOCOUNT ON

UPDATE [dbo].[gesCobro] SET
	[Descripcion] = @Descripcion,
	[Activo] = @Activo,
	[Devolucion] = @Devolucion,
	[Periodo] = @Periodo
WHERE
	[CodCobro] = @CodCobro

--endregion


