

--region [dbo].[pa_UpdategesProducto]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesProducto]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesProducto]
	@CodProducto uniqueidentifier,
	@CodGrupo int,
	@CodFamilia int,
	@CodZona int,
	@Descripcion varchar(100),
	@Activo bit,
	@Precio decimal(18, 2)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesProducto] SET
	[CodGrupo] = @CodGrupo,
	[CodFamilia] = @CodFamilia,
	[CodZona] = @CodZona,
	[Descripcion] = @Descripcion,
	[Activo] = @Activo,
	[Precio] = @Precio
WHERE
	[CodProducto] = @CodProducto

--endregion


