

--region [dbo].[pa_UpdategesArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesArqueo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesArqueo]
	@CodArqueo uniqueidentifier,
	@Orden int,
	@Fecha datetime,
	@CodTrabajador int,
	@Trabajador varchar(150),
	@CodLocal int,
	@Centro varchar(100),
	@CodDispositivo int,
	@Dispositivo varchar(100),
	@Comprobado bit,
	@Dia datetime,
	@CodPeriodo int,
	@Periodo char(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesArqueo] SET
	[Orden] = @Orden,
	[Fecha] = @Fecha,
	[CodTrabajador] = @CodTrabajador,
	[Trabajador] = @Trabajador,
	[CodLocal] = @CodLocal,
	[Centro] = @Centro,
	[CodDispositivo] = @CodDispositivo,
	[Dispositivo] = @Dispositivo,
	[Comprobado] = @Comprobado,
	[Dia] = @Dia,
	[CodPeriodo] = @CodPeriodo,
	[Periodo] = @Periodo
WHERE
	[CodArqueo] = @CodArqueo

--endregion


