

--region [dbo].[pa_UpdategesZona]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesZona]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesZona]
	@CodZona int,
	@CodLocal int,
	@CodDispositivo int,
	@CodActividad int,
	@Nombre varchar(100),
	@Activa bit,
	@Tipo char(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesZonas] SET
	[CodLocal] = @CodLocal,
	[CodDispositivo] = @CodDispositivo,
	[CodActividad] = @CodActividad,
	[Nombre] = @Nombre,
	[Activa] = @Activa,
	[Tipo] = @Tipo
WHERE
	[CodZona] = @CodZona

--endregion


