

--region [dbo].[pa_UpdateGesArticuloClaseConEscandallo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdateGesArticuloClaseConEscandallo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdateGesArticuloClaseConEscandallo]
	@CodClaseHijo int,
	@CodClasePadre int,
	@Codigo int,
	@Cantidad decimal(18, 4),
	@CodMagnitud int
AS

SET NOCOUNT ON

UPDATE [dbo].[GesArticuloClaseConEscandallo] SET
	[CodClaseHijo] = @CodClaseHijo,
	[CodClasePadre] = @CodClasePadre,
	[Cantidad] = @Cantidad,
	[CodMagnitud] = @CodMagnitud
WHERE
	[Codigo] = @Codigo

--endregion


