

--region [dbo].[pa_UpdategesCatalogo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesCatalogo]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesCatalogo]
	@CodCatalogo int,
	@CodProveedor int,
	@CodArticulo int,
	@CodFormatoPedido int,
	@CodEmpaquetado int,
	@Precio decimal(18, 4),
	@Pedir bit,
	@IVA decimal(18, 2),
	@Debe_haber decimal(18, 2),
	@Importe decimal(18, 4),
	@Contenido_unidad decimal(18, 2),
	@Contenido_caja decimal(18, 2),
	@PedirCajas bit,
	@Preferente bit,
	@PrecioUltimoCompra decimal(18, 2),
	@PrecioMedioCompra decimal(18, 2)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesCatalogo] SET
	[CodProveedor] = @CodProveedor,
	[CodArticulo] = @CodArticulo,
	[CodFormatoPedido] = @CodFormatoPedido,
	[CodEmpaquetado] = @CodEmpaquetado,
	[Precio] = @Precio,
	[Pedir] = @Pedir,
	[IVA] = @IVA,
	[Debe_haber] = @Debe_haber,
	[Importe] = @Importe,
	[Contenido_unidad] = @Contenido_unidad,
	[Contenido_caja] = @Contenido_caja,
	[PedirCajas] = @PedirCajas,
	[Preferente] = @Preferente,
	[PrecioUltimoCompra] = @PrecioUltimoCompra,
	[PrecioMedioCompra] = @PrecioMedioCompra
WHERE
	[CodCatalogo] = @CodCatalogo

--endregion


