

--region [dbo].[pa_UpdategesEstatu]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesEstatu]
-- Date Generated: martes, 05 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesEstatu]
	@CodEstatus int,
	@Descripcion varchar(50),
	@Activo bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesEstatus] SET
	[Descripcion] = @Descripcion,
	[Activo] = @Activo
WHERE
	[CodEstatus] = @CodEstatus

--endregion


