

--region [dbo].[pa_UpdateTotalArqueo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdateTotalArqueo]
-- Date Generated: jueves, 11 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdateTotalArqueo]
	@Fecha datetime,
	@Total decimal(18, 0),
	@Codigo bigint
AS

SET NOCOUNT ON

UPDATE [dbo].[TotalArqueo] SET
	[Fecha] = @Fecha,
	[Total] = @Total
WHERE
	[Codigo] = @Codigo

--endregion


