

--region [dbo].[pa_UpdategesPeriodo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesPeriodo]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesPeriodo]
	@CodPeriodo int,
	@Descripcion char(50),
	@Inicio datetime,
	@Final datetime
AS

SET NOCOUNT ON

UPDATE [dbo].[gesPeriodos] SET
	[Descripcion] = @Descripcion,
	[Inicio] = @Inicio,
	[Final] = @Final
WHERE
	[CodPeriodo] = @CodPeriodo

--endregion


