

--region [dbo].[pa_UpdategesLocal]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesLocal]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesLocal]
	@CodLocal int,
	@Nombre varchar(100),
	@Activo bit,
	@Direccion varchar(150),
	@Localidad varchar(50),
	@Provincia varchar(50),
	@CIF varchar(20),
	@Telefono char(20)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesLocal] SET
	[Nombre] = @Nombre,
	[Activo] = @Activo,
	[Direccion] = @Direccion,
	[Localidad] = @Localidad,
	[Provincia] = @Provincia,
	[CIF] = @CIF,
	[Telefono] = @Telefono
WHERE
	[CodLocal] = @CodLocal

--endregion


