

--region [dbo].[pa_UpdategesArticuloClase]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesArticuloClase]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesArticuloClase]
	@CodClase int,
	@Descripcion varchar(100),
	@Activo bit,
	@ConEscandallo bit,
	@Cantidad decimal(18, 4),
	@CodMagnitud int
AS

SET NOCOUNT ON

UPDATE [dbo].[gesArticuloClase] SET
	[Descripcion] = @Descripcion,
	[Activo] = @Activo,
	[ConEscandallo] = @ConEscandallo,
	[Cantidad] = @Cantidad,
	[CodMagnitud] = @CodMagnitud
WHERE
	[CodClase] = @CodClase

--endregion


