

--region [dbo].[pa_UpdategesFichaje]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesFichaje]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesFichaje]
	@CodFichaje uniqueidentifier,
	@CodTrabajador int,
	@Nombre varchar(100),
	@Apellidos varchar(100),
	@Entrada datetime,
	@Salida datetime,
	@CodPeriodo int,
	@Periodo char(50),
	@CodLocal int,
	@Centro varchar(100),
	@CodZona int,
	@Zona varchar(100),
	@CodDispositivo int,
	@Estado char(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesFichaje] SET
	[CodTrabajador] = @CodTrabajador,
	[Nombre] = @Nombre,
	[Apellidos] = @Apellidos,
	[Entrada] = @Entrada,
	[Salida] = @Salida,
	[CodPeriodo] = @CodPeriodo,
	[Periodo] = @Periodo,
	[CodLocal] = @CodLocal,
	[Centro] = @Centro,
	[CodZona] = @CodZona,
	[Zona] = @Zona,
	[CodDispositivo] = @CodDispositivo,
	[Estado] = @Estado
WHERE
	[CodFichaje] = @CodFichaje

--endregion


