

--region [dbo].[pa_UpdategesSeguridad]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesSeguridad]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesSeguridad]
	@CodSeguridad int,
	@Descripcion varchar(50),
	@Activa bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesSeguridad] SET
	[Descripcion] = @Descripcion,
	[Activa] = @Activa
WHERE
	[CodSeguridad] = @CodSeguridad

--endregion


