

--region [dbo].[pa_UpdategesAnulacionTipo]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesAnulacionTipo]
-- Date Generated: jueves, 30 de junio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesAnulacionTipo]
	@CodTipo int,
	@Descripcion char(100),
	@Resta bit,
	@Activo bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesAnulacionTipo] SET
	[Descripcion] = @Descripcion,
	[Resta] = @Resta,
	[Activo] = @Activo
WHERE
	[CodTipo] = @CodTipo

--endregion


