

--region [dbo].[pa_UpdategesCliente]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesCliente]
-- Date Generated: miércoles, 06 de julio de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesCliente]
	@CodCliente int,
	@Nombre varchar(50),
	@Apellidos varchar(100),
	@Empresa varchar(100),
	@Activo bit,
	@CIF char(50),
	@Direccion varchar(100),
	@Localidad varchar(50),
	@Provincia varchar(50),
	@CP char(10),
	@CodClase int,
	@Telefono1 char(10)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesCliente] SET
	[Nombre] = @Nombre,
	[Apellidos] = @Apellidos,
	[Empresa] = @Empresa,
	[Activo] = @Activo,
	[CIF] = @CIF,
	[Direccion] = @Direccion,
	[Localidad] = @Localidad,
	[Provincia] = @Provincia,
	[CP] = @CP,
	[CodClase] = @CodClase,
	[Telefono1] = @Telefono1
WHERE
	[CodCliente] = @CodCliente

--endregion


