

--region [dbo].[pa_UpdategesFamilia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesFamilia]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesFamilia]
	@CodFamilia int,
	@Descripcion varchar(100),
	@CodGrupo int,
	@Activa bit,
	@CodZona int
AS

SET NOCOUNT ON

UPDATE [dbo].[gesFamilia] SET
	[Descripcion] = @Descripcion,
	[CodGrupo] = @CodGrupo,
	[Activa] = @Activa,
	[CodZona] = @CodZona
WHERE
	[CodFamilia] = @CodFamilia

--endregion


