

--region [dbo].[pa_UpdategesPedidoDetalle]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesPedidoDetalle]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesPedidoDetalle]
	@CodDetalle uniqueidentifier,
	@CodPedido uniqueidentifier,
	@CodArticulo int,
	@CodCatalogo int,
	@Debe_haber decimal(18, 4),
	@Tenemos decimal(18, 4),
	@Pedimos decimal(18, 4),
	@Pedido datetime,
	@PresentacionUnidades decimal(18, 4),
	@PresentacionPrecio decimal(18, 4),
	@PresentacionFormatoPedido nvarchar(100),
	@PresentacionFormatoEnvase nvarchar(100),
	@PresentacionFormatoEmpaquetado nvarchar(100),
	@Recibido datetime,
	@Recibi bit,
	@Pedido_por varchar(50),
	@Recibido_por varchar(50),
	@Precio decimal(18, 4),
	@Subtotal decimal(18, 2),
	@Descuento decimal(18, 4),
	@IVA decimal(18, 2),
	@Observaciones nvarchar(200),
	@Cajas decimal(18, 4)
AS

SET NOCOUNT ON

UPDATE [dbo].[gesPedidoDetalle] SET
	[CodPedido] = @CodPedido,
	[CodArticulo] = @CodArticulo,
	[CodCatalogo] = @CodCatalogo,
	[Debe_haber] = @Debe_haber,
	[Tenemos] = @Tenemos,
	[Pedimos] = @Pedimos,
	[Pedido] = @Pedido,
	[PresentacionUnidades] = @PresentacionUnidades,
	[PresentacionPrecio] = @PresentacionPrecio,
	[PresentacionFormatoPedido] = @PresentacionFormatoPedido,
	[PresentacionFormatoEnvase] = @PresentacionFormatoEnvase,
	[PresentacionFormatoEmpaquetado] = @PresentacionFormatoEmpaquetado,
	[Recibido] = @Recibido,
	[Recibi] = @Recibi,
	[Pedido_por] = @Pedido_por,
	[Recibido_por] = @Recibido_por,
	[Precio] = @Precio,
	[Subtotal] = @Subtotal,
	[Descuento] = @Descuento,
	[IVA] = @IVA,
	[Observaciones] = @Observaciones,
	[Cajas] = @Cajas
WHERE
	[CodDetalle] = @CodDetalle

--endregion


