

--region [dbo].[pa_UpdategesProducto_Num]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   andres using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[pa_UpdategesProducto_Num]
-- Date Generated: domingo, 21 de agosto de 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[pa_UpdategesProducto_Num]
	@CodProducto uniqueidentifier,
	@CodGrupo int,
	@CodFamilia int,
	@CodZona int,
	@CodProducto_Num int,
	@Descripcion varchar(100),
	@Activo bit,
	@Precio decimal(18, 2),
	@ConEscandallo bit
AS

SET NOCOUNT ON

UPDATE [dbo].[gesProducto_Num] SET
	[CodProducto] = @CodProducto,
	[CodGrupo] = @CodGrupo,
	[CodFamilia] = @CodFamilia,
	[CodZona] = @CodZona,
	[Descripcion] = @Descripcion,
	[Activo] = @Activo,
	[Precio] = @Precio,
	[ConEscandallo] = @ConEscandallo
WHERE
	[CodProducto_Num] = @CodProducto_Num

--endregion


