//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsPedidoArt
    {
        public int CodArticulo { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<int> CodProveedor { get; set; }
        public Nullable<int> CodCatalogo { get; set; }
        public Nullable<System.Guid> CodPedido { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PUC { get; set; }
        public Nullable<decimal> PMC { get; set; }
        public Nullable<int> N { get; set; }
        public Nullable<decimal> Importe_Compra { get; set; }
        public Nullable<decimal> CantidadPedida { get; set; }
        public Nullable<int> CodClase { get; set; }
    
        public virtual gesArticulo gesArticulo { get; set; }
    }
}
