//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsClaseArtConEscandallo
    {
        public int IDClasePrincipal { get; set; }
        public int CodClase { get; set; }
        public int IDClasePadre { get; set; }
        public Nullable<bool> CalculoPorPeso { get; set; }
        public Nullable<bool> CalculoPorRacion { get; set; }
        public string ClaseArticuloPadre { get; set; }
        public string ClaseArticulo { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> CantidadOriginal { get; set; }
        public Nullable<decimal> PNRacion { get; set; }
        public Nullable<decimal> PHRacion { get; set; }
        public Nullable<decimal> PCantidad { get; set; }
        public Nullable<decimal> HCantidad { get; set; }
        public Nullable<decimal> PrecioCoste { get; set; }
        public Nullable<int> CodCatalogo { get; set; }
        public Nullable<decimal> Importe_Catalogo { get; set; }
        public Nullable<decimal> Importe_Compra { get; set; }
        public Nullable<decimal> CantidadPedida { get; set; }
        public Nullable<int> CodArticulo { get; set; }
        public Nullable<decimal> Contenido_Caja { get; set; }
        public Nullable<decimal> ContenidoUnidad { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<int> CodProveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> CodMagnitud { get; set; }
        public Nullable<System.Guid> CodPedido { get; set; }
        public string Magnitud { get; set; }
        public Nullable<decimal> Conversion_Magnitud { get; set; }
        public string TipoConversion { get; set; }
        public string Proveedor { get; set; }
        public string NombreArticulo { get; set; }
        public Nullable<decimal> PrecioCosteCantidad { get; set; }
        public Nullable<decimal> CosteClaseArticuloPorPreparacion { get; set; }
        public Nullable<decimal> CosteClaseArticulo { get; set; }
        public Nullable<decimal> Importe_Catalogo_Unidad { get; set; }
    }
}
