//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesArticulo()
        {
            this.gesCatalogo = new HashSet<gesCatalogo>();
            this.gesPedidoDetalle = new HashSet<gesPedidoDetalle>();
        }
    
        public int CodArticulo { get; set; }
        public Nullable<int> CodGrupo { get; set; }
        public Nullable<int> CodFamilia { get; set; }
        public Nullable<int> CodEnvase { get; set; }
        public Nullable<int> CodMagnitud { get; set; }
        public Nullable<int> CodGrupoCompra { get; set; }
        public Nullable<int> CodSectorPedido { get; set; }
        public Nullable<int> CodClase { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<decimal> Contenido_unidad { get; set; }
        public Nullable<decimal> Contenido_caja { get; set; }
        public Nullable<decimal> Existencias { get; set; }
        public Nullable<decimal> Debe_haber { get; set; }
        public Nullable<decimal> PrecioUltimoCompra { get; set; }
        public Nullable<decimal> PrecioMedioCompra { get; set; }
        public Nullable<decimal> FactorEnvase { get; set; }
        public Nullable<decimal> CantidadEnvase { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
    
        public virtual ConsPedidoArt ConsPedidoArt { get; set; }
        public virtual gesArticuloClase gesArticuloClase { get; set; }
        public virtual gesArticuloFamilia gesArticuloFamilia { get; set; }
        public virtual gesEnvase gesEnvase { get; set; }
        public virtual gesGrupoCompra gesGrupoCompra { get; set; }
        public virtual gesMagnitud gesMagnitud { get; set; }
        public virtual gesSectorPedido gesSectorPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesCatalogo> gesCatalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesPedidoDetalle> gesPedidoDetalle { get; set; }
    }
}
