//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesArqueo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesArqueo()
        {
            this.gesArqueoDetalle = new HashSet<gesArqueoDetalle>();
        }
    
        public System.Guid CodArqueo { get; set; }
        public int Orden { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> CodTrabajador { get; set; }
        public string Trabajador { get; set; }
        public Nullable<int> CodLocal { get; set; }
        public string Centro { get; set; }
        public Nullable<int> CodDispositivo { get; set; }
        public string Dispositivo { get; set; }
        public Nullable<bool> Comprobado { get; set; }
        public Nullable<System.DateTime> Dia { get; set; }
        public Nullable<int> CodPeriodo { get; set; }
        public string Periodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesArqueoDetalle> gesArqueoDetalle { get; set; }
    }
}
