//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesAnulaciones
    {
        public int CodAnulacion { get; set; }
        public Nullable<int> CodTrabajador { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CodProducto { get; set; }
        public int CodTipo { get; set; }
    }
}
