//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesArqueoDetalle
    {
        public System.Guid CodDetalle { get; set; }
        public Nullable<System.Guid> CodArqueo { get; set; }
        public string Realidad { get; set; }
        public Nullable<decimal> Contado { get; set; }
        public string Registro { get; set; }
        public Nullable<decimal> Vendido { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public Nullable<int> Periodo { get; set; }
    
        public virtual gesArqueo gesArqueo { get; set; }
    }
}
