//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesCola
    {
        public int CodCola { get; set; }
        public Nullable<System.Guid> CodFactura { get; set; }
        public Nullable<int> Factura { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<int> Mesa { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Trabajador { get; set; }
        public string Estado { get; set; }
        public string Operacion { get; set; }
    }
}
