//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesCatalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesCatalogo()
        {
            this.gesListaCompra = new HashSet<gesListaCompra>();
        }
    
        public int CodCatalogo { get; set; }
        public Nullable<int> CodProveedor { get; set; }
        public Nullable<int> CodArticulo { get; set; }
        public Nullable<int> CodFormatoPedido { get; set; }
        public Nullable<int> CodEmpaquetado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Pedir { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Debe_haber { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Contenido_unidad { get; set; }
        public Nullable<decimal> Contenido_caja { get; set; }
        public Nullable<bool> PedirCajas { get; set; }
        public Nullable<bool> Preferente { get; set; }
        public Nullable<decimal> PrecioUltimoCompra { get; set; }
        public Nullable<decimal> PrecioMedioCompra { get; set; }
    
        public virtual gesArticulo gesArticulo { get; set; }
        public virtual gesEmpaquetado gesEmpaquetado { get; set; }
        public virtual gesFormatoPedido gesFormatoPedido { get; set; }
        public virtual gesProveedores gesProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesListaCompra> gesListaCompra { get; set; }
    }
}
