//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesDispositivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesDispositivo()
        {
            this.gesFacTique_Num = new HashSet<gesFacTique_Num>();
            this.gesZonas = new HashSet<gesZonas>();
        }
    
        public int CodDispositivo { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
        public string Tipo { get; set; }
        public bool Imprime_comanda { get; set; }
        public bool Imprime_tique { get; set; }
        public bool Imprime_factura { get; set; }
        public bool Abre_cajon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesFacTique_Num> gesFacTique_Num { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesZonas> gesZonas { get; set; }
    }
}
