//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesFamilia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesFamilia()
        {
            this.gesProducto_Num = new HashSet<gesProducto_Num>();
        }
    
        public int CodFamilia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CodGrupo { get; set; }
        public bool Activa { get; set; }
        public Nullable<int> CodZona { get; set; }
    
        public virtual gesGrupo gesGrupo { get; set; }
        public virtual gesZonas gesZonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesProducto_Num> gesProducto_Num { get; set; }
    }
}
