//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesFacTique
    {
        public System.Guid CodDetalle { get; set; }
        public Nullable<System.Guid> CodFactura { get; set; }
        public Nullable<System.Guid> CodProducto { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> Unidad { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> CodTrabajador { get; set; }
        public string Suceso { get; set; }
        public string Operacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Orden { get; set; }
        public Nullable<int> CodDispositivo { get; set; }
        public string Dispositivo { get; set; }
        public string Actividad { get; set; }
        public Nullable<int> CodZona { get; set; }
        public string Zona { get; set; }
        public Nullable<int> CodGrupo { get; set; }
        public string Grupo { get; set; }
        public Nullable<int> CodFamilia { get; set; }
        public string Familia { get; set; }
        public Nullable<int> CodActividad { get; set; }
        public Nullable<int> Mesa { get; set; }
        public string Cliente { get; set; }
        public string Trabajador { get; set; }
        public Nullable<int> CodPeriodo { get; set; }
        public string Periodo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.Guid> Relacion { get; set; }
        public string Estadio { get; set; }
        public Nullable<int> CodCola { get; set; }
    
        public virtual gesFactura gesFactura { get; set; }
    }
}
