//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesFactura()
        {
            this.gesFacTique = new HashSet<gesFacTique>();
            this.gesFacTique_Num = new HashSet<gesFacTique_Num>();
        }
    
        public System.Guid CodFactura { get; set; }
        public Nullable<System.DateTime> Abierta { get; set; }
        public Nullable<System.DateTime> Facturada { get; set; }
        public Nullable<System.DateTime> Cobrada { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Mesa { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public Nullable<System.Guid> CodTrabajador { get; set; }
        public string Estado { get; set; }
        public Nullable<int> CodLocal { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> CodPeriodo { get; set; }
        public string Operador { get; set; }
        public string Dispositivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesFacTique> gesFacTique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesFacTique_Num> gesFacTique_Num { get; set; }
        public virtual gesLocal gesLocal { get; set; }
        public virtual gesPeriodos gesPeriodos { get; set; }
        public virtual gesTrabajador gesTrabajador { get; set; }
    }
}
