//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesListaCompra
    {
        public System.Guid CodListaPedido { get; set; }
        public Nullable<int> CodCatalogo { get; set; }
        public Nullable<int> CodTrabajadorCrea { get; set; }
        public Nullable<int> CodTrabajadorModifica { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> NumeroPedido { get; set; }
        public Nullable<bool> SeleccionadoPedir { get; set; }
        public Nullable<decimal> PedidoUnidades { get; set; }
        public string PedidoFormato { get; set; }
        public Nullable<decimal> PedidoPrecio { get; set; }
        public Nullable<decimal> RealUnidades { get; set; }
        public string RealTextoUnidades { get; set; }
        public Nullable<decimal> RealCajas { get; set; }
        public string RealTextoCajas { get; set; }
        public Nullable<decimal> RealPrecioUnidad { get; set; }
        public Nullable<decimal> RealPrecioCaja { get; set; }
        public Nullable<decimal> RealImporte { get; set; }
        public string RealObservaciones { get; set; }
        public string RealObservacionesGenerales { get; set; }
    
        public virtual gesCatalogo gesCatalogo { get; set; }
    }
}
