//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesPersona
    {
        public System.Guid CodPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string DNI { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> CodPoblacion { get; set; }
        public string SS { get; set; }
        public string Genero { get; set; }
        public string Movil { get; set; }
        public string Fijo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
    }
}
