//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesReservas
    {
        public System.Guid CodReserva { get; set; }
        public Nullable<System.DateTime> Llegada { get; set; }
        public Nullable<System.DateTime> Reservada { get; set; }
        public Nullable<System.DateTime> Sentados { get; set; }
        public Nullable<System.DateTime> Realizada { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public string Cliente { get; set; }
        public string Pax { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> CodTrabajador { get; set; }
        public string Trabajador { get; set; }
        public Nullable<int> CodLocal { get; set; }
        public string Centro { get; set; }
        public Nullable<int> CodZona { get; set; }
        public string Zona { get; set; }
        public string Señal { get; set; }
    }
}
