//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesTrabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesTrabajador()
        {
            this.gesFacTique_Num = new HashSet<gesFacTique_Num>();
            this.gesFactura = new HashSet<gesFactura>();
        }
    
        public System.Guid CodTrabajador { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Fijo { get; set; }
        public string Movil { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string CP { get; set; }
        public string DNI { get; set; }
        public string SS { get; set; }
        public string Banco { get; set; }
        public string Clave { get; set; }
        public Nullable<int> CodEstatus { get; set; }
        public Nullable<int> CodSeguridad { get; set; }
    
        public virtual gesEstatus gesEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesFacTique_Num> gesFacTique_Num { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesFactura> gesFactura { get; set; }
        public virtual gesSeguridad gesSeguridad { get; set; }
    }
}
