//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEmpresarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class gesZonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gesZonas()
        {
            this.gesFamilia = new HashSet<gesFamilia>();
        }
    
        public int CodZona { get; set; }
        public Nullable<int> CodLocal { get; set; }
        public Nullable<int> CodDispositivo { get; set; }
        public Nullable<int> CodActividad { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activa { get; set; }
        public string Tipo { get; set; }
    
        public virtual gesActividades gesActividades { get; set; }
        public virtual gesDispositivo gesDispositivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gesFamilia> gesFamilia { get; set; }
        public virtual gesLocal gesLocal { get; set; }
    }
}
