CREATE TABLE [dbo].[ConsClaseArtConEscandallo] (
    [IDClasePrincipal]                 INT              NOT NULL,
    [CodClase]                         INT              NOT NULL,
    [IDClasePadre]                     INT              NOT NULL,
    [CalculoPorPeso]                   BIT              NULL,
    [CalculoPorRacion]                 BIT              NULL,
    [ClaseArticuloPadre]               NVARCHAR (200)   NULL,
    [ClaseArticulo]                    NVARCHAR (200)   NULL,
    [Factor]                           DECIMAL (18, 4)  NULL,
    [Cantidad]                         DECIMAL (18, 4)  NULL,
    [CantidadOriginal]                 DECIMAL (18, 4)  NULL,
    [PNRacion]                         DECIMAL (18, 4)  NULL,
    [PHRacion]                         DECIMAL (18, 4)  NULL,
    [PCantidad]                        DECIMAL (18, 4)  NULL,
    [HCantidad]                        DECIMAL (18, 4)  NULL,
    [PrecioCoste]                      DECIMAL (18, 4)  NULL,
    [CodCatalogo]                      INT              NULL,
    [Importe_Catalogo]                 DECIMAL (18, 4)  NULL,
    [Importe_Compra]                   DECIMAL (18, 4)  NULL,
    [CantidadPedida]                   DECIMAL (18, 4)  NULL,
    [CodArticulo]                      INT              NULL,
    [Contenido_Caja]                   DECIMAL (18, 4)  NULL,
    [ContenidoUnidad]                  DECIMAL (18, 4)  NULL,
    [PrecioCompra]                     DECIMAL (18, 4)  NULL,
    [CodProveedor]                     INT              NULL,
    [Fecha]                            DATETIME         NULL,
    [CodMagnitud]                      INT              NULL,
    [CodPedido]                        UNIQUEIDENTIFIER NULL,
    [Magnitud]                         NVARCHAR (200)   NULL,
    [Conversion_Magnitud]              DECIMAL (18, 4)  NULL,
    [TipoConversion]                   NVARCHAR (100)   NULL,
    [Proveedor]                        NVARCHAR (200)   NULL,
    [NombreArticulo]                   NVARCHAR (200)   NULL,
    [PrecioCosteCantidad]              DECIMAL (18, 4)  NULL,
    [CosteClaseArticuloPorPreparacion] DECIMAL (18, 4)  NULL,
    [CosteClaseArticulo]               DECIMAL (18, 4)  NULL,
    [Importe_Catalogo_Unidad]          DECIMAL (18, 4)  NULL,
    CONSTRAINT [PK_ConsClaseArtConEscandallo] PRIMARY KEY CLUSTERED ([IDClasePrincipal] ASC, [CodClase] ASC, [IDClasePadre] ASC)
);

