CREATE TABLE [dbo].[gesFacTique] (
    [CodDetalle]     UNIQUEIDENTIFIER NOT NULL,
    [CodFactura]     UNIQUEIDENTIFIER NULL,
    [CodProducto]    UNIQUEIDENTIFIER NULL,
    [Detalle]        VARCHAR (150)    NULL,
    [Unidad]         INT              NULL,
    [Importe]        DECIMAL (18, 2)  NULL,
    [SubTotal]       DECIMAL (18, 2)  NULL,
    [CodTrabajador]  INT              NULL,
    [Suceso]         CHAR (50)        NULL,
    [Operacion]      CHAR (50)        NULL,
    [Fecha]          DATETIME         NULL,
    [Orden]          INT              NOT NULL,
    [CodDispositivo] INT              NULL,
    [Dispositivo]    CHAR (50)        NULL,
    [Actividad]      VARCHAR (100)    NULL,
    [CodZona]        INT              NULL,
    [Zona]           VARCHAR (100)    NULL,
    [CodGrupo]       INT              NULL,
    [Grupo]          VARCHAR (100)    NULL,
    [CodFamilia]     INT              NULL,
    [Familia]        VARCHAR (100)    NULL,
    [CodActividad]   INT              NULL,
    [Mesa]           INT              NULL,
    [Cliente]        VARCHAR (100)    NULL,
    [Trabajador]     VARCHAR (100)    NULL,
    [CodPeriodo]     INT              NULL,
    [Periodo]        CHAR (50)        NULL,
    [Activo]         BIT              NULL,
    [Relacion]       UNIQUEIDENTIFIER NULL,
    [Estadio]        CHAR (50)        NULL,
    [CodCola]        INT              NULL,
    CONSTRAINT [PK_gesFacTique] PRIMARY KEY CLUSTERED ([CodDetalle] ASC),
    CONSTRAINT [FK_gesFacTique_gesFactura] FOREIGN KEY ([CodFactura]) REFERENCES [dbo].[gesFactura] ([CodFactura])
);

